/* Generated by tools/fetch_fgc_data.py from results.first.global. Do not edit by hand. */
self.FGC_DATA = {
"event": {
"id": "FGC_2026-FGC-CMP",
"name": "2026 FIRST Global Challenge",
"tz": "Asia/Seoul",
"source": "results.first.global, fetched 2026-10-10 04:01 UTC",
"rev": "cdd247abd8"
},
"teams": {
"AFG": {
"name": "Team Afghanistan",
"flag": "flags/af.png",
"country": "Afghanistan"
},
"ALB": {
"name": "Team Albania",
"flag": "flags/al.png",
"country": "Albania"
},
"ALG": {
"name": "Team Algeria",
"flag": "flags/dz.png",
"country": "Algeria"
},
"ANG": {
"name": "Team Angola",
"flag": "flags/ao.png",
"country": "Angola"
},
"ANT": {
"name": "Team Antigua and Barbuda",
"flag": "flags/ag.png",
"country": "Antigua and Barbuda"
},
"ARG": {
"name": "Team Argentina",
"flag": "flags/ar.png",
"country": "Argentina"
},
"ARU": {
"name": "Team Aruba",
"flag": "flags/aw.png",
"country": "Aruba"
},
"ASA": {
"name": "Team American Samoa",
"flag": "flags/as.png",
"country": "American Samoa"
},
"AUS": {
"name": "Team Australia",
"flag": "flags/au.png",
"country": "Australia"
},
"AUT": {
"name": "Team Austria",
"flag": "flags/at.png",
"country": "Austria"
},
"AZE": {
"name": "Team Azerbaijan",
"flag": "flags/az.png",
"country": "Azerbaijan"
},
"BAN": {
"name": "Team Bangladesh",
"flag": "flags/bd.png",
"country": "Bangladesh"
},
"BAR": {
"name": "Team Barbados",
"flag": "flags/bb.png",
"country": "Barbados"
},
"BEL": {
"name": "Team Belgium",
"flag": "flags/be.png",
"country": "Belgium"
},
"BEN": {
"name": "Team Benin",
"flag": "flags/bj.png",
"country": "Benin"
},
"BHU": {
"name": "Team Bhutan",
"flag": "flags/bt.png",
"country": "Bhutan"
},
"BIH": {
"name": "Team Bosnia and Herzegovina",
"flag": "flags/ba.png",
"country": "Bosnia and Herzegovina"
},
"BIZ": {
"name": "Team Belize",
"flag": "flags/bz.png",
"country": "Belize"
},
"BLR": {
"name": "Team Belarus",
"flag": "flags/by.png",
"country": "Belarus"
},
"BOL": {
"name": "Team Bolivia",
"flag": "flags/bo.png",
"country": "Bolivia"
},
"BOT": {
"name": "Team Botswana",
"flag": "flags/bw.png",
"country": "Botswana"
},
"BRA": {
"name": "Team Brazil",
"flag": "flags/br.png",
"country": "Brazil"
},
"BRU": {
"name": "Team Brunei Darussalam",
"flag": "flags/bn.png",
"country": "Brunei Darussalam"
},
"BUL": {
"name": "Team Bulgaria",
"flag": "flags/bg.png",
"country": "Bulgaria"
},
"BUR": {
"name": "Team Burkina Faso",
"flag": "flags/bf.png",
"country": "Burkina Faso"
},
"CAF": {
"name": "Team Central African Republic",
"flag": "flags/cf.png",
"country": "Central African Republic"
},
"CAM": {
"name": "Team Cambodia",
"flag": "flags/kh.png",
"country": "Cambodia"
},
"CAN": {
"name": "Team Canada",
"flag": "flags/ca.png",
"country": "Canada"
},
"CAY": {
"name": "Team Cayman Islands",
"flag": "flags/ky.png",
"country": "Cayman Islands"
},
"CGO": {
"name": "Team Congo",
"flag": "flags/cg.png",
"country": "Congo"
},
"CHA": {
"name": "Team Chad",
"flag": "flags/td.png",
"country": "Chad"
},
"CHI": {
"name": "Team Chile",
"flag": "flags/cl.png",
"country": "Chile"
},
"CHN": {
"name": "Team People's Republic of China",
"flag": "flags/cn.png",
"country": "People's Republic of China"
},
"CIV": {
"name": "Team Côte d'Ivoire",
"flag": "flags/ci.png",
"country": "Côte d'Ivoire"
},
"CMR": {
"name": "Team Cameroon",
"flag": "flags/cm.png",
"country": "Cameroon"
},
"COD": {
"name": "Team Democratic Republic of the Congo",
"flag": "flags/cd.png",
"country": "Democratic Republic of the Congo"
},
"COK": {
"name": "Team Cook Islands",
"flag": "flags/ck.png",
"country": "Cook Islands"
},
"COL": {
"name": "Team Colombia",
"flag": "flags/co.png",
"country": "Colombia"
},
"COM": {
"name": "Team Comoros",
"flag": "flags/km.png",
"country": "Comoros"
},
"CPV": {
"name": "Team Cabo Verde",
"flag": "flags/cv.png",
"country": "Cabo Verde"
},
"CRC": {
"name": "Team Costa Rica",
"flag": "flags/cr.png",
"country": "Costa Rica"
},
"CRO": {
"name": "Team Croatia",
"flag": "flags/hr.png",
"country": "Croatia"
},
"CUB": {
"name": "Team Cuba",
"flag": "flags/cu.png",
"country": "Cuba"
},
"CZE": {
"name": "Team Czechia",
"flag": "flags/cz.png",
"country": "Czechia"
},
"DEN": {
"name": "Team Denmark",
"flag": "flags/dk.png",
"country": "Denmark"
},
"DJI": {
"name": "Team Djibouti",
"flag": "flags/dj.png",
"country": "Djibouti"
},
"DMA": {
"name": "Team Dominica",
"flag": "flags/dm.png",
"country": "Dominica"
},
"DOM": {
"name": "Team Dominican Republic",
"flag": "flags/do.png",
"country": "Dominican Republic"
},
"ECU": {
"name": "Team Ecuador",
"flag": "flags/ec.png",
"country": "Ecuador"
},
"EGY": {
"name": "Team Egypt",
"flag": "flags/eg.png",
"country": "Egypt"
},
"ERI": {
"name": "Team Eritrea",
"flag": "flags/er.png",
"country": "Eritrea"
},
"ESA": {
"name": "Team El Salvador",
"flag": "flags/sv.png",
"country": "El Salvador"
},
"ESP": {
"name": "Team Spain",
"flag": "flags/es.png",
"country": "Spain"
},
"EST": {
"name": "Team Estonia",
"flag": "flags/ee.png",
"country": "Estonia"
},
"ETH": {
"name": "Team Ethiopia",
"flag": "flags/et.png",
"country": "Ethiopia"
},
"FIJ": {
"name": "Team Fiji",
"flag": "flags/fj.png",
"country": "Fiji"
},
"FIN": {
"name": "Team Finland",
"flag": "flags/fi.png",
"country": "Finland"
},
"FRA": {
"name": "Team France",
"flag": "flags/fr.png",
"country": "France"
},
"FSM": {
"name": "Team Federated States of Micronesia",
"flag": "flags/fm.png",
"country": "Federated States of Micronesia"
},
"GAB": {
"name": "Team Gabon",
"flag": "flags/ga.png",
"country": "Gabon"
},
"GAM": {
"name": "Team Gambia",
"flag": "flags/gm.png",
"country": "Gambia"
},
"GBR": {
"name": "Team Great Britain",
"flag": "flags/gb.png",
"country": "Great Britain"
},
"GBS": {
"name": "Team Guinea-Bissau",
"flag": "flags/gw.png",
"country": "Guinea-Bissau"
},
"GEO": {
"name": "Team Georgia",
"flag": "flags/ge.png",
"country": "Georgia"
},
"GEQ": {
"name": "Team Equatorial Guinea",
"flag": "flags/gq.png",
"country": "Equatorial Guinea"
},
"GER": {
"name": "Team Germany",
"flag": "flags/de.png",
"country": "Germany"
},
"GHA": {
"name": "Team Ghana",
"flag": "flags/gh.png",
"country": "Ghana"
},
"GRE": {
"name": "Team Greece",
"flag": "flags/gr.png",
"country": "Greece"
},
"GRN": {
"name": "Team Grenada",
"flag": "flags/gd.png",
"country": "Grenada"
},
"GUA": {
"name": "Team Guatemala",
"flag": "flags/gt.png",
"country": "Guatemala"
},
"GUI": {
"name": "Team Guinea",
"flag": "flags/gn.png",
"country": "Guinea"
},
"GUM": {
"name": "Team Guam",
"flag": "flags/gu.png",
"country": "Guam"
},
"GUY": {
"name": "Team Guyana",
"flag": "flags/gy.png",
"country": "Guyana"
},
"HAI": {
"name": "Team Haiti",
"flag": "flags/ht.png",
"country": "Haiti"
},
"HKG": {
"name": "Team Hong Kong, China",
"flag": "flags/hk.png",
"country": "Hong Kong, China"
},
"HON": {
"name": "Team Honduras",
"flag": "flags/hn.png",
"country": "Honduras"
},
"HPE": {
"name": "Team Hope (Refugees)",
"flag": "flags/10_hope.png"
},
"HUN": {
"name": "Team Hungary",
"flag": "flags/hu.png",
"country": "Hungary"
},
"INA": {
"name": "Team Indonesia",
"flag": "flags/id.png",
"country": "Indonesia"
},
"IND": {
"name": "Team India",
"flag": "flags/in.png",
"country": "India"
},
"IRI": {
"name": "Team Islamic Republic of Iran",
"flag": "flags/ir.png",
"country": "Islamic Republic of Iran"
},
"IRL": {
"name": "Team Ireland",
"flag": "flags/ie.png",
"country": "Ireland"
},
"IRQ": {
"name": "Team Iraq",
"flag": "flags/iq.png",
"country": "Iraq"
},
"ISR": {
"name": "Team Israel",
"flag": "flags/il.png",
"country": "Israel"
},
"ISV": {
"name": "Team U.S. Virgin Islands",
"flag": "flags/vi.png",
"country": "U.S. Virgin Islands"
},
"ITA": {
"name": "Team Italy",
"flag": "flags/it.png",
"country": "Italy"
},
"IVB": {
"name": "Team British Virgin Islands",
"flag": "flags/vg.png",
"country": "British Virgin Islands"
},
"JAM": {
"name": "Team Jamaica",
"flag": "flags/jm.png",
"country": "Jamaica"
},
"JOR": {
"name": "Team Jordan",
"flag": "flags/jo.png",
"country": "Jordan"
},
"JPN": {
"name": "Team Japan",
"flag": "flags/jp.png",
"country": "Japan"
},
"KAZ": {
"name": "Team Kazakhstan",
"flag": "flags/kz.png",
"country": "Kazakhstan"
},
"KEN": {
"name": "Team Kenya",
"flag": "flags/ke.png",
"country": "Kenya"
},
"KGZ": {
"name": "Team Kyrgyzstan",
"flag": "flags/kg.png",
"country": "Kyrgyzstan"
},
"KIR": {
"name": "Team Kiribati",
"flag": "flags/ki.png",
"country": "Kiribati"
},
"KOR": {
"name": "Team Republic of Korea",
"flag": "flags/kr.png",
"country": "Republic of Korea"
},
"KOS": {
"name": "Team Kosovo",
"flag": "flags/xk.png",
"country": "Kosovo"
},
"LAO": {
"name": "Team Lao People's Democratic Republic",
"flag": "flags/la.png",
"country": "Lao People's Democratic Republic"
},
"LAT": {
"name": "Team Latvia",
"flag": "flags/lv.png",
"country": "Latvia"
},
"LBA": {
"name": "Team Libya",
"flag": "flags/ly.png",
"country": "Libya"
},
"LBN": {
"name": "Team Lebanon",
"flag": "flags/lb.png",
"country": "Lebanon"
},
"LBR": {
"name": "Team Liberia",
"flag": "flags/lr.png",
"country": "Liberia"
},
"LCA": {
"name": "Team Saint Lucia",
"flag": "flags/lc.png",
"country": "Saint Lucia"
},
"LES": {
"name": "Team Lesotho",
"flag": "flags/ls.png",
"country": "Lesotho"
},
"LTU": {
"name": "Team Lithuania",
"flag": "flags/lt.png",
"country": "Lithuania"
},
"LUX": {
"name": "Team Luxembourg",
"flag": "flags/lu.png",
"country": "Luxembourg"
},
"MAD": {
"name": "Team Madagascar",
"flag": "flags/mg.png",
"country": "Madagascar"
},
"MAR": {
"name": "Team Morocco",
"flag": "flags/ma.png",
"country": "Morocco"
},
"MAS": {
"name": "Team Malaysia",
"flag": "flags/my.png",
"country": "Malaysia"
},
"MAW": {
"name": "Team Malawi",
"flag": "flags/mw.png",
"country": "Malawi"
},
"MDA": {
"name": "Team Republic of Moldova",
"flag": "flags/md.png",
"country": "Republic of Moldova"
},
"MDV": {
"name": "Team Maldives",
"flag": "flags/mv.png",
"country": "Maldives"
},
"MEX": {
"name": "Team Mexico",
"flag": "flags/mx.png",
"country": "Mexico"
},
"MGL": {
"name": "Team Mongolia",
"flag": "flags/mn.png",
"country": "Mongolia"
},
"MHL": {
"name": "Team Marshall Islands",
"flag": "flags/mh.png",
"country": "Marshall Islands"
},
"MKD": {
"name": "Team North Macedonia",
"flag": "flags/mk.png",
"country": "North Macedonia"
},
"MLI": {
"name": "Team Mali",
"flag": "flags/ml.png",
"country": "Mali"
},
"MLT": {
"name": "Team Malta",
"flag": "flags/mt.png",
"country": "Malta"
},
"MNE": {
"name": "Team Montenegro",
"flag": "flags/me.png",
"country": "Montenegro"
},
"MOZ": {
"name": "Team Mozambique",
"flag": "flags/mz.png",
"country": "Mozambique"
},
"MRI": {
"name": "Team Mauritius",
"flag": "flags/mu.png",
"country": "Mauritius"
},
"MTN": {
"name": "Team Mauritania",
"flag": "flags/mr.png",
"country": "Mauritania"
},
"MYA": {
"name": "Team Myanmar",
"flag": "flags/mm.png",
"country": "Myanmar"
},
"NAM": {
"name": "Team Namibia",
"flag": "flags/na.png",
"country": "Namibia"
},
"NCA": {
"name": "Team Nicaragua",
"flag": "flags/ni.png",
"country": "Nicaragua"
},
"NED": {
"name": "Team Netherlands",
"flag": "flags/nl.png",
"country": "Netherlands"
},
"NEP": {
"name": "Team Nepal",
"flag": "flags/np.png",
"country": "Nepal"
},
"NGR": {
"name": "Team Nigeria",
"flag": "flags/ng.png",
"country": "Nigeria"
},
"NIG": {
"name": "Team Niger",
"flag": "flags/ne.png",
"country": "Niger"
},
"NOR": {
"name": "Team Norway",
"flag": "flags/no.png",
"country": "Norway"
},
"OMA": {
"name": "Team Oman",
"flag": "flags/om.png",
"country": "Oman"
},
"PAK": {
"name": "Team Pakistan",
"flag": "flags/pk.png",
"country": "Pakistan"
},
"PAN": {
"name": "Team Panama",
"flag": "flags/pa.png",
"country": "Panama"
},
"PAR": {
"name": "Team Paraguay",
"flag": "flags/py.png",
"country": "Paraguay"
},
"PER": {
"name": "Team Peru",
"flag": "flags/pe.png",
"country": "Peru"
},
"PHI": {
"name": "Team Philippines",
"flag": "flags/ph.png",
"country": "Philippines"
},
"PLE": {
"name": "Team Palestine",
"flag": "flags/ps.png",
"country": "Palestine"
},
"PNG": {
"name": "Team Papua New Guinea",
"flag": "flags/pg.png",
"country": "Papua New Guinea"
},
"POL": {
"name": "Team Poland",
"flag": "flags/pl.png",
"country": "Poland"
},
"POR": {
"name": "Team Portugal",
"flag": "flags/pt.png",
"country": "Portugal"
},
"PUR": {
"name": "Team Puerto Rico",
"flag": "flags/pr.png",
"country": "Puerto Rico"
},
"QAT": {
"name": "Team Qatar",
"flag": "flags/qa.png",
"country": "Qatar"
},
"ROU": {
"name": "Team Romania",
"flag": "flags/ro.png",
"country": "Romania"
},
"RSA": {
"name": "Team South Africa",
"flag": "flags/za.png",
"country": "South Africa"
},
"RUS": {
"name": "Team Russian Federation",
"flag": "flags/ru.png",
"country": "Russian Federation"
},
"RWA": {
"name": "Team Rwanda",
"flag": "flags/rw.png",
"country": "Rwanda"
},
"SEN": {
"name": "Team Senegal",
"flag": "flags/sn.png",
"country": "Senegal"
},
"SEY": {
"name": "Team Seychelles",
"flag": "flags/sc.png",
"country": "Seychelles"
},
"SKN": {
"name": "Team Saint Kitts and Nevis",
"flag": "flags/kn.png",
"country": "Saint Kitts and Nevis"
},
"SLE": {
"name": "Team Sierra Leone",
"flag": "flags/sl.png",
"country": "Sierra Leone"
},
"SLO": {
"name": "Team Slovenia",
"flag": "flags/si.png",
"country": "Slovenia"
},
"SOL": {
"name": "Team Solomon Islands",
"flag": "flags/sb.png",
"country": "Solomon Islands"
},
"SOM": {
"name": "Team Somalia",
"flag": "flags/so.png",
"country": "Somalia"
},
"SRB": {
"name": "Team Serbia",
"flag": "flags/rs.png",
"country": "Serbia"
},
"SRI": {
"name": "Team Sri Lanka",
"flag": "flags/lk.png",
"country": "Sri Lanka"
},
"SSD": {
"name": "Team South Sudan",
"flag": "flags/ss.png",
"country": "South Sudan"
},
"STP": {
"name": "Team São Tomé and Príncipe",
"flag": "flags/st.png",
"country": "São Tomé and Príncipe"
},
"SUD": {
"name": "Team Sudan",
"flag": "flags/sd.png",
"country": "Sudan"
},
"SVK": {
"name": "Team Slovakia",
"flag": "flags/sk.png",
"country": "Slovakia"
},
"SWE": {
"name": "Team Sweden",
"flag": "flags/se.png",
"country": "Sweden"
},
"SWZ": {
"name": "Team Eswatini",
"flag": "flags/sz.png",
"country": "Eswatini"
},
"SYR": {
"name": "Team Syrian Arab Republic",
"flag": "flags/sy.png",
"country": "Syrian Arab Republic"
},
"TAN": {
"name": "Team United Republic of Tanzania",
"flag": "flags/tz.png",
"country": "United Republic of Tanzania"
},
"TGA": {
"name": "Team Tonga",
"flag": "flags/to.png",
"country": "Tonga"
},
"THA": {
"name": "Team Thailand",
"flag": "flags/th.png",
"country": "Thailand"
},
"TJK": {
"name": "Team Tajikistan",
"flag": "flags/tj.png",
"country": "Tajikistan"
},
"TKM": {
"name": "Team Turkmenistan",
"flag": "flags/tm.png",
"country": "Turkmenistan"
},
"TLS": {
"name": "Team Timor-Leste",
"flag": "flags/tl.png",
"country": "Timor-Leste"
},
"TOG": {
"name": "Team Togo",
"flag": "flags/tg.png",
"country": "Togo"
},
"TPE": {
"name": "Team Chinese Taipei",
"flag": "flags/tw.png",
"country": "Chinese Taipei"
},
"TTO": {
"name": "Team Trinidad and Tobago",
"flag": "flags/tt.png",
"country": "Trinidad and Tobago"
},
"TUN": {
"name": "Team Tunisia",
"flag": "flags/tn.png",
"country": "Tunisia"
},
"TUR": {
"name": "Team Türkiye",
"flag": "flags/tr.png",
"country": "Türkiye"
},
"UAE": {
"name": "Team United Arab Emirates",
"flag": "flags/ae.png",
"country": "United Arab Emirates"
},
"UGA": {
"name": "Team Uganda",
"flag": "flags/ug.png",
"country": "Uganda"
},
"UKR": {
"name": "Team Ukraine",
"flag": "flags/ua.png",
"country": "Ukraine"
},
"URU": {
"name": "Team Uruguay",
"flag": "flags/uy.png",
"country": "Uruguay"
},
"USA": {
"name": "Team United States of America",
"flag": "flags/us.png",
"country": "United States of America"
},
"UZB": {
"name": "Team Uzbekistan",
"flag": "flags/uz.png",
"country": "Uzbekistan"
},
"VAN": {
"name": "Team Vanuatu",
"flag": "flags/vu.png",
"country": "Vanuatu"
},
"VEN": {
"name": "Team Venezuela",
"flag": "flags/ve.png",
"country": "Venezuela"
},
"VIE": {
"name": "Team Vietnam",
"flag": "flags/vn.png",
"country": "Vietnam"
},
"VIN": {
"name": "Team Saint Vincent and the Grenadines",
"flag": "flags/vc.png",
"country": "Saint Vincent and the Grenadines"
},
"YEM": {
"name": "Team Yemen",
"flag": "flags/ye.png",
"country": "Yemen"
},
"ZAM": {
"name": "Team Zambia",
"flag": "flags/zm.png",
"country": "Zambia"
},
"ZIM": {
"name": "Team Zimbabwe",
"flag": "flags/zw.png",
"country": "Zimbabwe"
}
},
"matches": [
{
"id": "t2-1",
"type": "ranking",
"number": 1,
"name": "Ranking Match 1",
"field": 1,
"time": "2026-10-08T11:15:00.900+09:00",
"red": [
"SLE",
"ARU",
"AFG"
],
"blue": [
"ANG",
"SRB",
"NOR"
],
"played": true
},
{
"id": "t2-3",
"type": "ranking",
"number": 3,
"name": "Ranking Match 3",
"field": 3,
"time": "2026-10-08T11:15:00.900+09:00",
"red": [
"JPN",
"COD",
"COL"
],
"blue": [
"LTU",
"CPV",
"MAW"
],
"played": true
},
{
"id": "t2-2",
"type": "ranking",
"number": 2,
"name": "Ranking Match 2",
"field": 4,
"time": "2026-10-08T11:15:00.900+09:00",
"red": [
"URU",
"CRC",
"RUS"
],
"blue": [
"KAZ",
"VAN",
"KOS"
],
"played": true
},
{
"id": "t2-4",
"type": "ranking",
"number": 4,
"name": "Ranking Match 4",
"field": 2,
"time": "2026-10-08T11:23:00.900+09:00",
"red": [
"MLI",
"BOT",
"ETH"
],
"blue": [
"BOL",
"MHL",
"SWE"
],
"played": true
},
{
"id": "t2-6",
"type": "ranking",
"number": 6,
"name": "Ranking Match 6",
"field": 3,
"time": "2026-10-08T11:23:00.900+09:00",
"red": [
"FSM",
"BLR",
"UKR"
],
"blue": [
"CAM",
"GEO",
"MNE"
],
"played": true
},
{
"id": "t2-5",
"type": "ranking",
"number": 5,
"name": "Ranking Match 5",
"field": 5,
"time": "2026-10-08T11:23:00.900+09:00",
"red": [
"POL",
"PNG",
"CAY"
],
"blue": [
"MAD",
"MYA",
"PHI"
],
"played": true
},
{
"id": "t2-7",
"type": "ranking",
"number": 7,
"name": "Ranking Match 7",
"field": 1,
"time": "2026-10-08T11:31:00.900+09:00",
"red": [
"ASA",
"ECU",
"CIV"
],
"blue": [
"TGA",
"CRO",
"ANT"
],
"played": true
},
{
"id": "t2-9",
"type": "ranking",
"number": 9,
"name": "Ranking Match 9",
"field": 3,
"time": "2026-10-08T11:31:00.900+09:00",
"red": [
"KOR",
"MKD",
"KIR"
],
"blue": [
"BUL",
"BIZ",
"SYR"
],
"played": true
},
{
"id": "t2-8",
"type": "ranking",
"number": 8,
"name": "Ranking Match 8",
"field": 4,
"time": "2026-10-08T11:31:00.900+09:00",
"red": [
"TPE",
"YEM",
"FRA"
],
"blue": [
"CHN",
"ZAM",
"BRA"
],
"played": true
},
{
"id": "t2-10",
"type": "ranking",
"number": 10,
"name": "Ranking Match 10",
"field": 2,
"time": "2026-10-08T11:39:00.900+09:00",
"red": [
"SKN",
"VIN",
"INA"
],
"blue": [
"PAN",
"GUM",
"COM"
],
"played": true
},
{
"id": "t2-12",
"type": "ranking",
"number": 12,
"name": "Ranking Match 12",
"field": 3,
"time": "2026-10-08T11:39:00.900+09:00",
"red": [
"KEN",
"MDA",
"FIN"
],
"blue": [
"MRI",
"TTO",
"IRL"
],
"played": true
},
{
"id": "t2-11",
"type": "ranking",
"number": 11,
"name": "Ranking Match 11",
"field": 5,
"time": "2026-10-08T11:39:00.900+09:00",
"red": [
"AZE",
"MDV",
"MTN"
],
"blue": [
"LCA",
"SSD",
"RWA"
],
"played": true
},
{
"id": "t2-13",
"type": "ranking",
"number": 13,
"name": "Ranking Match 13",
"field": 1,
"time": "2026-10-08T11:47:00.900+09:00",
"red": [
"ALG",
"SOL",
"SUD"
],
"blue": [
"UZB",
"HUN",
"MEX"
],
"played": true
},
{
"id": "t2-15",
"type": "ranking",
"number": 15,
"name": "Ranking Match 15",
"field": 3,
"time": "2026-10-08T11:47:00.900+09:00",
"red": [
"CMR",
"DMA",
"RSA"
],
"blue": [
"SOM",
"JOR",
"TJK"
],
"played": true
},
{
"id": "t2-14",
"type": "ranking",
"number": 14,
"name": "Ranking Match 14",
"field": 4,
"time": "2026-10-08T11:47:00.900+09:00",
"red": [
"GBS",
"BAN",
"ZIM"
],
"blue": [
"PAK",
"IVB",
"SEN"
],
"played": true
},
{
"id": "t2-16",
"type": "ranking",
"number": 16,
"name": "Ranking Match 16",
"field": 2,
"time": "2026-10-08T11:55:00.900+09:00",
"red": [
"GAB",
"HPE",
"BHU"
],
"blue": [
"NIG",
"COK",
"ITA"
],
"played": true
},
{
"id": "t2-18",
"type": "ranking",
"number": 18,
"name": "Ranking Match 18",
"field": 3,
"time": "2026-10-08T11:55:00.900+09:00",
"red": [
"CZE",
"TUR",
"GHA"
],
"blue": [
"TKM",
"ESP",
"DEN"
],
"played": true
},
{
"id": "t2-17",
"type": "ranking",
"number": 17,
"name": "Ranking Match 17",
"field": 5,
"time": "2026-10-08T11:55:00.900+09:00",
"red": [
"BEN",
"ALB",
"ESA"
],
"blue": [
"BAR",
"CGO",
"EST"
],
"played": true
},
{
"id": "t2-19",
"type": "ranking",
"number": 19,
"name": "Ranking Match 19",
"field": 1,
"time": "2026-10-08T12:03:00.900+09:00",
"red": [
"BUR",
"SLO",
"CUB"
],
"blue": [
"PAR",
"NAM",
"IND"
],
"played": true
},
{
"id": "t2-21",
"type": "ranking",
"number": 21,
"name": "Ranking Match 21",
"field": 3,
"time": "2026-10-08T12:03:00.900+09:00",
"red": [
"GUY",
"BRU",
"GRE"
],
"blue": [
"LAT",
"CHA",
"GUA"
],
"played": true
},
{
"id": "t2-20",
"type": "ranking",
"number": 20,
"name": "Ranking Match 20",
"field": 4,
"time": "2026-10-08T12:03:00.900+09:00",
"red": [
"HAI",
"ERI",
"USA"
],
"blue": [
"EGY",
"LBN",
"BEL"
],
"played": true
},
{
"id": "t2-22",
"type": "ranking",
"number": 22,
"name": "Ranking Match 22",
"field": 2,
"time": "2026-10-08T12:11:00.900+09:00",
"red": [
"BIH",
"JAM",
"LBR"
],
"blue": [
"IRQ",
"ROU",
"TOG"
],
"played": true
},
{
"id": "t2-24",
"type": "ranking",
"number": 24,
"name": "Ranking Match 24",
"field": 3,
"time": "2026-10-08T12:11:00.900+09:00",
"red": [
"SVK",
"CHI",
"GRN"
],
"blue": [
"HON",
"IRI",
"NCA"
],
"played": true
},
{
"id": "t2-23",
"type": "ranking",
"number": 23,
"name": "Ranking Match 23",
"field": 5,
"time": "2026-10-08T12:11:00.900+09:00",
"red": [
"MLT",
"MGL",
"MAS"
],
"blue": [
"MAR",
"KGZ",
"NGR"
],
"played": true
},
{
"id": "t2-25",
"type": "ranking",
"number": 25,
"name": "Ranking Match 25",
"field": 1,
"time": "2026-10-08T12:19:00.900+09:00",
"red": [
"ISV",
"TUN",
"GBR"
],
"blue": [
"PER",
"THA",
"PLE"
],
"played": true
},
{
"id": "t2-27",
"type": "ranking",
"number": 27,
"name": "Ranking Match 27",
"field": 3,
"time": "2026-10-08T12:19:00.900+09:00",
"red": [
"ISR",
"DJI",
"TLS"
],
"blue": [
"DOM",
"FIJ",
"TAN"
],
"played": true
},
{
"id": "t2-26",
"type": "ranking",
"number": 26,
"name": "Ranking Match 26",
"field": 4,
"time": "2026-10-08T12:19:00.900+09:00",
"red": [
"PUR",
"LBA",
"MOZ"
],
"blue": [
"STP",
"OMA",
"HKG"
],
"played": true
},
{
"id": "t2-28",
"type": "ranking",
"number": 28,
"name": "Ranking Match 28",
"field": 2,
"time": "2026-10-08T12:27:00.900+09:00",
"red": [
"QAT",
"CAF",
"AUT"
],
"blue": [
"LUX",
"UGA",
"SWZ"
],
"played": true
},
{
"id": "t2-30",
"type": "ranking",
"number": 30,
"name": "Ranking Match 30",
"field": 3,
"time": "2026-10-08T12:27:00.900+09:00",
"red": [
"GER",
"LAO",
"GUI"
],
"blue": [
"GEQ",
"SRI",
"SEY"
],
"played": true
},
{
"id": "t2-29",
"type": "ranking",
"number": 29,
"name": "Ranking Match 29",
"field": 5,
"time": "2026-10-08T12:27:00.900+09:00",
"red": [
"GAM",
"VEN",
"POR"
],
"blue": [
"CAN",
"AUS",
"ARG"
],
"played": true
},
{
"id": "t2-31",
"type": "ranking",
"number": 31,
"name": "Ranking Match 31",
"field": 1,
"time": "2026-10-08T12:35:00.900+09:00",
"red": [
"NEP",
"UAE",
"ECU"
],
"blue": [
"NED",
"LES",
"VIE"
],
"played": true
},
{
"id": "t2-33",
"type": "ranking",
"number": 33,
"name": "Ranking Match 33",
"field": 3,
"time": "2026-10-08T12:35:00.900+09:00",
"red": [
"MTN",
"MKD",
"ITA"
],
"blue": [
"PAK",
"ANT",
"PAN"
],
"played": true
},
{
"id": "t2-32",
"type": "ranking",
"number": 32,
"name": "Ranking Match 32",
"field": 4,
"time": "2026-10-08T12:35:00.900+09:00",
"red": [
"FRA",
"BOT",
"SLE"
],
"blue": [
"IVB",
"COM",
"KEN"
],
"played": true
},
{
"id": "t2-34",
"type": "ranking",
"number": 34,
"name": "Ranking Match 34",
"field": 2,
"time": "2026-10-08T12:43:00.900+09:00",
"red": [
"AZE",
"FIN",
"MHL"
],
"blue": [
"KOR",
"CMR",
"ALG"
],
"played": true
},
{
"id": "t2-36",
"type": "ranking",
"number": 36,
"name": "Ranking Match 36",
"field": 3,
"time": "2026-10-08T12:43:00.900+09:00",
"red": [
"SLO",
"TJK",
"ESP"
],
"blue": [
"ESA",
"COK",
"JPN"
],
"played": true
},
{
"id": "t2-35",
"type": "ranking",
"number": 35,
"name": "Ranking Match 35",
"field": 5,
"time": "2026-10-08T12:43:00.900+09:00",
"red": [
"CUB",
"VAN",
"SOM"
],
"blue": [
"ETH",
"GHA",
"LCA"
],
"played": true
},
{
"id": "t2-37",
"type": "ranking",
"number": 37,
"name": "Ranking Match 37",
"field": 1,
"time": "2026-10-08T12:51:00.900+09:00",
"red": [
"NOR",
"CAM",
"IRL"
],
"blue": [
"COL",
"CRO",
"CRC"
],
"played": true
},
{
"id": "t2-39",
"type": "ranking",
"number": 39,
"name": "Ranking Match 39",
"field": 3,
"time": "2026-10-08T12:51:00.900+09:00",
"red": [
"SSD",
"ANG",
"MLT"
],
"blue": [
"MLI",
"NIG",
"GUA"
],
"played": true
},
{
"id": "t2-38",
"type": "ranking",
"number": 38,
"name": "Ranking Match 38",
"field": 4,
"time": "2026-10-08T12:51:00.900+09:00",
"red": [
"GUY",
"USA",
"KAZ"
],
"blue": [
"JOR",
"LBR",
"BAR"
],
"played": true
},
{
"id": "t2-40",
"type": "ranking",
"number": 40,
"name": "Ranking Match 40",
"field": 2,
"time": "2026-10-08T14:00:00.900+09:00",
"red": [
"DEN",
"BIH",
"PAR"
],
"blue": [
"CGO",
"GBS",
"HPE"
],
"played": true
},
{
"id": "t2-42",
"type": "ranking",
"number": 42,
"name": "Ranking Match 42",
"field": 3,
"time": "2026-10-08T14:00:00.900+09:00",
"red": [
"CZE",
"CAY",
"IRI"
],
"blue": [
"TPE",
"TUN",
"GRE"
],
"played": true
},
{
"id": "t2-41",
"type": "ranking",
"number": 41,
"name": "Ranking Match 41",
"field": 5,
"time": "2026-10-08T14:00:00.900+09:00",
"red": [
"CPV",
"BOL",
"PHI"
],
"blue": [
"ZIM",
"MNE",
"CHA"
],
"played": true
},
{
"id": "t2-43",
"type": "ranking",
"number": 43,
"name": "Ranking Match 43",
"field": 1,
"time": "2026-10-08T14:08:00.900+09:00",
"red": [
"BEL",
"SVK",
"MAW"
],
"blue": [
"PLE",
"UZB",
"MAD"
],
"played": true
},
{
"id": "t2-45",
"type": "ranking",
"number": 45,
"name": "Ranking Match 45",
"field": 3,
"time": "2026-10-08T14:08:00.900+09:00",
"red": [
"TUR",
"DOM",
"BRA"
],
"blue": [
"EST",
"SWZ",
"VEN"
],
"played": true
},
{
"id": "t2-44",
"type": "ranking",
"number": 44,
"name": "Ranking Match 44",
"field": 4,
"time": "2026-10-08T14:08:00.900+09:00",
"red": [
"CHN",
"KIR",
"TTO"
],
"blue": [
"HUN",
"COD",
"ARU"
],
"played": true
},
{
"id": "t2-46",
"type": "ranking",
"number": 46,
"name": "Ranking Match 46",
"field": 2,
"time": "2026-10-08T14:16:00.900+09:00",
"red": [
"MAR",
"AUT",
"MEX"
],
"blue": [
"LBA",
"NAM",
"HAI"
],
"played": true
},
{
"id": "t2-48",
"type": "ranking",
"number": 48,
"name": "Ranking Match 48",
"field": 3,
"time": "2026-10-08T14:16:00.900+09:00",
"red": [
"SOL",
"HKG",
"ISR"
],
"blue": [
"POL",
"MDA",
"AFG"
],
"played": true
},
{
"id": "t2-47",
"type": "ranking",
"number": 47,
"name": "Ranking Match 47",
"field": 5,
"time": "2026-10-08T14:16:00.900+09:00",
"red": [
"NGR",
"GBR",
"MRI"
],
"blue": [
"INA",
"LUX",
"BAN"
],
"played": true
},
{
"id": "t2-49",
"type": "ranking",
"number": 49,
"name": "Ranking Match 49",
"field": 1,
"time": "2026-10-08T14:24:00.900+09:00",
"red": [
"VIN",
"UAE",
"DJI"
],
"blue": [
"GRN",
"ERI",
"CIV"
],
"played": true
},
{
"id": "t2-51",
"type": "ranking",
"number": 51,
"name": "Ranking Match 51",
"field": 3,
"time": "2026-10-08T14:24:00.900+09:00",
"red": [
"TOG",
"ISV",
"ARG"
],
"blue": [
"SWE",
"OMA",
"ALB"
],
"played": true
},
{
"id": "t2-50",
"type": "ranking",
"number": 50,
"name": "Ranking Match 50",
"field": 4,
"time": "2026-10-08T14:24:00.900+09:00",
"red": [
"SRB",
"GEO",
"HON"
],
"blue": [
"TKM",
"POR",
"KGZ"
],
"played": true
},
{
"id": "t2-52",
"type": "ranking",
"number": 52,
"name": "Ranking Match 52",
"field": 2,
"time": "2026-10-08T14:32:00.900+09:00",
"red": [
"SRI",
"RWA",
"ROU"
],
"blue": [
"CAF",
"NED",
"BRU"
],
"played": true
},
{
"id": "t2-54",
"type": "ranking",
"number": 54,
"name": "Ranking Match 54",
"field": 3,
"time": "2026-10-08T14:32:00.900+09:00",
"red": [
"CAN",
"URU",
"BHU"
],
"blue": [
"MGL",
"EGY",
"CHI"
],
"played": true
},
{
"id": "t2-53",
"type": "ranking",
"number": 53,
"name": "Ranking Match 53",
"field": 5,
"time": "2026-10-08T14:32:00.900+09:00",
"red": [
"PNG",
"GEQ",
"BEN"
],
"blue": [
"SYR",
"MDV",
"TAN"
],
"played": true
},
{
"id": "t2-55",
"type": "ranking",
"number": 55,
"name": "Ranking Match 55",
"field": 1,
"time": "2026-10-08T14:40:00.900+09:00",
"red": [
"TLS",
"NCA",
"KOS"
],
"blue": [
"VIE",
"SEY",
"BLR"
],
"played": true
},
{
"id": "t2-57",
"type": "ranking",
"number": 57,
"name": "Ranking Match 57",
"field": 3,
"time": "2026-10-08T14:40:00.900+09:00",
"red": [
"LAT",
"RUS",
"GAM"
],
"blue": [
"RSA",
"SEN",
"LES"
],
"played": true
},
{
"id": "t2-56",
"type": "ranking",
"number": 56,
"name": "Ranking Match 56",
"field": 4,
"time": "2026-10-08T14:40:00.900+09:00",
"red": [
"MOZ",
"IRQ",
"THA"
],
"blue": [
"NEP",
"SKN",
"YEM"
],
"played": true
},
{
"id": "t2-58",
"type": "ranking",
"number": 58,
"name": "Ranking Match 58",
"field": 2,
"time": "2026-10-08T14:48:00.900+09:00",
"red": [
"UGA",
"GAB",
"BUR"
],
"blue": [
"BIZ",
"UKR",
"GER"
],
"played": true
},
{
"id": "t2-60",
"type": "ranking",
"number": 60,
"name": "Ranking Match 60",
"field": 3,
"time": "2026-10-08T14:48:00.900+09:00",
"red": [
"STP",
"LBN",
"ASA"
],
"blue": [
"SUD",
"LAO",
"LTU"
],
"played": true
},
{
"id": "t2-59",
"type": "ranking",
"number": 59,
"name": "Ranking Match 59",
"field": 5,
"time": "2026-10-08T14:48:00.900+09:00",
"red": [
"AUS",
"FIJ",
"GUM"
],
"blue": [
"DMA",
"PUR",
"BUL"
],
"played": true
},
{
"id": "t2-61",
"type": "ranking",
"number": 61,
"name": "Ranking Match 61",
"field": 1,
"time": "2026-10-08T14:56:00.900+09:00",
"red": [
"MAS",
"PER",
"FSM"
],
"blue": [
"TGA",
"IND",
"MYA"
],
"played": true
},
{
"id": "t2-63",
"type": "ranking",
"number": 63,
"name": "Ranking Match 63",
"field": 3,
"time": "2026-10-08T14:56:00.900+09:00",
"red": [
"CMR",
"GRE",
"TUR"
],
"blue": [
"BOT",
"BIH",
"KIR"
],
"played": true
},
{
"id": "t2-62",
"type": "ranking",
"number": 62,
"name": "Ranking Match 62",
"field": 4,
"time": "2026-10-08T14:56:00.900+09:00",
"red": [
"ZAM",
"AZE",
"QAT"
],
"blue": [
"GUI",
"JAM",
"PLE"
],
"played": true
},
{
"id": "t2-64",
"type": "ranking",
"number": 64,
"name": "Ranking Match 64",
"field": 2,
"time": "2026-10-08T15:04:00.900+09:00",
"red": [
"IVB",
"HKG",
"HPE"
],
"blue": [
"MNE",
"IRI",
"INA"
],
"played": true
},
{
"id": "t2-66",
"type": "ranking",
"number": 66,
"name": "Ranking Match 66",
"field": 3,
"time": "2026-10-08T15:04:00.900+09:00",
"red": [
"VAN",
"COK",
"SRB"
],
"blue": [
"TUN",
"UAE",
"CHA"
],
"played": true
},
{
"id": "t2-65",
"type": "ranking",
"number": 65,
"name": "Ranking Match 65",
"field": 5,
"time": "2026-10-08T15:04:00.900+09:00",
"red": [
"NOR",
"GHA",
"SVK"
],
"blue": [
"MLI",
"PAK",
"KOR"
],
"played": true
},
{
"id": "t2-67",
"type": "ranking",
"number": 67,
"name": "Ranking Match 67",
"field": 1,
"time": "2026-10-08T15:12:00.900+09:00",
"red": [
"DJI",
"CAY",
"CPV"
],
"blue": [
"ISV",
"ITA",
"SOM"
],
"played": true
},
{
"id": "t2-69",
"type": "ranking",
"number": 69,
"name": "Ranking Match 69",
"field": 3,
"time": "2026-10-08T15:12:00.900+09:00",
"red": [
"BOL",
"VIN",
"CAF"
],
"blue": [
"ISR",
"GEO",
"GUY"
],
"played": true
},
{
"id": "t2-68",
"type": "ranking",
"number": 68,
"name": "Ranking Match 68",
"field": 4,
"time": "2026-10-08T15:12:00.900+09:00",
"red": [
"CUB",
"CAM",
"NIG"
],
"blue": [
"CHN",
"EST",
"AFG"
],
"played": true
},
{
"id": "t2-70",
"type": "ranking",
"number": 70,
"name": "Ranking Match 70",
"field": 2,
"time": "2026-10-08T15:20:00.900+09:00",
"red": [
"CRO",
"HAI",
"CZE"
],
"blue": [
"KAZ",
"SYR",
"MRI"
],
"played": true
},
{
"id": "t2-72",
"type": "ranking",
"number": 72,
"name": "Ranking Match 72",
"field": 3,
"time": "2026-10-08T15:20:00.900+09:00",
"red": [
"IRL",
"BRA",
"TKM"
],
"blue": [
"SRI",
"MEX",
"ECU"
],
"played": true
},
{
"id": "t2-71",
"type": "ranking",
"number": 71,
"name": "Ranking Match 71",
"field": 5,
"time": "2026-10-08T15:20:00.900+09:00",
"red": [
"OMA",
"HUN",
"TLS"
],
"blue": [
"GRN",
"ETH",
"BRU"
],
"played": true
},
{
"id": "t2-73",
"type": "ranking",
"number": 73,
"name": "Ranking Match 73",
"field": 1,
"time": "2026-10-08T15:28:00.900+09:00",
"red": [
"EGY",
"IRQ",
"PNG"
],
"blue": [
"TPE",
"PAR",
"RUS"
],
"played": true
},
{
"id": "t2-75",
"type": "ranking",
"number": 75,
"name": "Ranking Match 75",
"field": 3,
"time": "2026-10-08T15:28:00.900+09:00",
"red": [
"GBR",
"BUL",
"CHI"
],
"blue": [
"SLO",
"GER",
"COL"
],
"played": true
},
{
"id": "t2-74",
"type": "ranking",
"number": 74,
"name": "Ranking Match 74",
"field": 4,
"time": "2026-10-08T15:28:00.900+09:00",
"red": [
"KEN",
"MAR",
"URU"
],
"blue": [
"GUA",
"ARG",
"JOR"
],
"played": true
},
{
"id": "t2-76",
"type": "ranking",
"number": 76,
"name": "Ranking Match 76",
"field": 2,
"time": "2026-10-08T15:45:00.900+09:00",
"red": [
"ROU",
"SEN",
"NEP"
],
"blue": [
"NCA",
"LBN",
"SOL"
],
"played": true
},
{
"id": "t2-78",
"type": "ranking",
"number": 78,
"name": "Ranking Match 78",
"field": 3,
"time": "2026-10-08T15:45:00.900+09:00",
"red": [
"SLE",
"LCA",
"DOM"
],
"blue": [
"COD",
"ANT",
"PUR"
],
"played": true
},
{
"id": "t2-77",
"type": "ranking",
"number": 77,
"name": "Ranking Match 77",
"field": 5,
"time": "2026-10-08T15:45:00.900+09:00",
"red": [
"DEN",
"SWZ",
"TOG"
],
"blue": [
"BEL",
"ESA",
"FSM"
],
"played": true
},
{
"id": "t2-79",
"type": "ranking",
"number": 79,
"name": "Ranking Match 79",
"field": 1,
"time": "2026-10-08T15:53:00.900+09:00",
"red": [
"TJK",
"TGA",
"UZB"
],
"blue": [
"NAM",
"LUX",
"LAO"
],
"played": true
},
{
"id": "t2-81",
"type": "ranking",
"number": 81,
"name": "Ranking Match 81",
"field": 3,
"time": "2026-10-08T15:53:00.900+09:00",
"red": [
"POL",
"JPN",
"MTN"
],
"blue": [
"STP",
"CRC",
"USA"
],
"played": true
},
{
"id": "t2-80",
"type": "ranking",
"number": 80,
"name": "Ranking Match 80",
"field": 4,
"time": "2026-10-08T15:53:00.900+09:00",
"red": [
"SSD",
"ALG",
"SKN"
],
"blue": [
"LES",
"MAS",
"GUI"
],
"played": true
},
{
"id": "t2-82",
"type": "ranking",
"number": 82,
"name": "Ranking Match 82",
"field": 2,
"time": "2026-10-08T16:01:00.900+09:00",
"red": [
"BAR",
"MOZ",
"PER"
],
"blue": [
"GAB",
"PHI",
"ARU"
],
"played": true
},
{
"id": "t2-84",
"type": "ranking",
"number": 84,
"name": "Ranking Match 84",
"field": 3,
"time": "2026-10-08T16:01:00.900+09:00",
"red": [
"TTO",
"ASA",
"BIZ"
],
"blue": [
"BHU",
"GUM",
"ZAM"
],
"played": true
},
{
"id": "t2-83",
"type": "ranking",
"number": 83,
"name": "Ranking Match 83",
"field": 5,
"time": "2026-10-08T16:01:00.900+09:00",
"red": [
"LBR",
"MDA",
"ESP"
],
"blue": [
"PAN",
"MAW",
"RSA"
],
"played": true
},
{
"id": "t2-85",
"type": "ranking",
"number": 85,
"name": "Ranking Match 85",
"field": 1,
"time": "2026-10-08T16:09:00.900+09:00",
"red": [
"YEM",
"MLT",
"ERI"
],
"blue": [
"RWA",
"JAM",
"ZIM"
],
"played": true
},
{
"id": "t2-87",
"type": "ranking",
"number": 87,
"name": "Ranking Match 87",
"field": 3,
"time": "2026-10-08T16:09:00.900+09:00",
"red": [
"LAT",
"MYA",
"BUR"
],
"blue": [
"SEY",
"DMA",
"CGO"
],
"played": true
},
{
"id": "t2-86",
"type": "ranking",
"number": 86,
"name": "Ranking Match 86",
"field": 4,
"time": "2026-10-08T16:09:00.900+09:00",
"red": [
"MKD",
"VEN",
"TAN"
],
"blue": [
"BAN",
"AUT",
"ALB"
],
"played": true
},
{
"id": "t2-88",
"type": "ranking",
"number": 88,
"name": "Ranking Match 88",
"field": 2,
"time": "2026-10-08T16:17:00.900+09:00",
"red": [
"NGR",
"THA",
"POR"
],
"blue": [
"LBA",
"BEN",
"VIE"
],
"played": true
},
{
"id": "t2-90",
"type": "ranking",
"number": 90,
"name": "Ranking Match 90",
"field": 3,
"time": "2026-10-08T16:17:00.900+09:00",
"red": [
"MAD",
"ANG",
"IND"
],
"blue": [
"CAN",
"MDV",
"NED"
],
"played": true
},
{
"id": "t2-89",
"type": "ranking",
"number": 89,
"name": "Ranking Match 89",
"field": 5,
"time": "2026-10-08T16:17:00.900+09:00",
"red": [
"UKR",
"GBS",
"GAM"
],
"blue": [
"GEQ",
"KGZ",
"SWE"
],
"played": true
},
{
"id": "t2-91",
"type": "ranking",
"number": 91,
"name": "Ranking Match 91",
"field": 1,
"time": "2026-10-08T16:25:00.900+09:00",
"red": [
"MGL",
"QAT",
"MHL"
],
"blue": [
"FIJ",
"LTU",
"KOS"
],
"played": true
},
{
"id": "t2-93",
"type": "ranking",
"number": 93,
"name": "Ranking Match 93",
"field": 3,
"time": "2026-10-08T16:25:00.900+09:00",
"red": [
"BLR",
"AZE",
"COM"
],
"blue": [
"AUS",
"JOR",
"SLO"
],
"played": true
},
{
"id": "t2-92",
"type": "ranking",
"number": 92,
"name": "Ranking Match 92",
"field": 4,
"time": "2026-10-08T16:25:00.900+09:00",
"red": [
"CIV",
"FRA",
"UGA"
],
"blue": [
"SUD",
"FIN",
"HON"
],
"played": true
},
{
"id": "t2-94",
"type": "ranking",
"number": 94,
"name": "Ranking Match 94",
"field": 2,
"time": "2026-10-08T16:33:00.900+09:00",
"red": [
"MRI",
"PLE",
"OMA"
],
"blue": [
"DEN",
"BRA",
"SOM"
],
"played": true
},
{
"id": "t2-96",
"type": "ranking",
"number": 96,
"name": "Ranking Match 96",
"field": 3,
"time": "2026-10-08T16:33:00.900+09:00",
"red": [
"LBN",
"LUX",
"IRQ"
],
"blue": [
"IRI",
"KOR",
"UAE"
],
"played": true
},
{
"id": "t2-95",
"type": "ranking",
"number": 95,
"name": "Ranking Match 95",
"field": 5,
"time": "2026-10-08T16:33:00.900+09:00",
"red": [
"LAO",
"MEX",
"CRO"
],
"blue": [
"PNG",
"BRU",
"NCA"
],
"played": true
},
{
"id": "t2-97",
"type": "ranking",
"number": 97,
"name": "Ranking Match 97",
"field": 1,
"time": "2026-10-08T16:41:00.900+09:00",
"red": [
"MAS",
"STP",
"SWZ"
],
"blue": [
"TLS",
"SEN",
"SLE"
],
"played": true
},
{
"id": "t2-99",
"type": "ranking",
"number": 99,
"name": "Ranking Match 99",
"field": 3,
"time": "2026-10-08T16:41:00.900+09:00",
"red": [
"INA",
"UZB",
"CHI"
],
"blue": [
"ESP",
"KIR",
"MAR"
],
"played": true
},
{
"id": "t2-98",
"type": "ranking",
"number": 98,
"name": "Ranking Match 98",
"field": 4,
"time": "2026-10-08T16:41:00.900+09:00",
"red": [
"PER",
"SRI",
"SSD"
],
"blue": [
"ARG",
"ANT",
"SOL"
],
"played": true
},
{
"id": "t2-100",
"type": "ranking",
"number": 100,
"name": "Ranking Match 100",
"field": 2,
"time": "2026-10-08T16:49:00.900+09:00",
"red": [
"NOR",
"GUI",
"ISR"
],
"blue": [
"PAR",
"URU",
"MOZ"
],
"played": true
},
{
"id": "t2-102",
"type": "ranking",
"number": 102,
"name": "Ranking Match 102",
"field": 3,
"time": "2026-10-08T16:49:00.900+09:00",
"red": [
"ASA",
"MKD",
"ISV"
],
"blue": [
"MLT",
"GRE",
"TJK"
],
"played": true
},
{
"id": "t2-101",
"type": "ranking",
"number": 101,
"name": "Ranking Match 101",
"field": 5,
"time": "2026-10-08T16:49:00.900+09:00",
"red": [
"EGY",
"GER",
"CZE"
],
"blue": [
"PHI",
"CAF",
"EST"
],
"played": true
},
{
"id": "t2-103",
"type": "ranking",
"number": 103,
"name": "Ranking Match 103",
"field": 1,
"time": "2026-10-08T16:57:00.900+09:00",
"red": [
"HKG",
"CHA",
"GUM"
],
"blue": [
"BAN",
"NEP",
"RWA"
],
"played": true
},
{
"id": "t2-105",
"type": "ranking",
"number": 105,
"name": "Ranking Match 105",
"field": 3,
"time": "2026-10-08T16:57:00.900+09:00",
"red": [
"ALG",
"SWE",
"ROU"
],
"blue": [
"KAZ",
"FSM",
"AUT"
],
"played": true
},
{
"id": "t2-104",
"type": "ranking",
"number": 104,
"name": "Ranking Match 104",
"field": 4,
"time": "2026-10-08T16:57:00.900+09:00",
"red": [
"DOM",
"BOL",
"CHN"
],
"blue": [
"BUL",
"GHA",
"MTN"
],
"played": true
},
{
"id": "t2-106",
"type": "ranking",
"number": 106,
"name": "Ranking Match 106",
"field": 2,
"time": "2026-10-08T17:05:00.900+09:00",
"red": [
"ITA",
"RSA",
"GUY"
],
"blue": [
"SKN",
"IRL",
"CAN"
],
"played": true
},
{
"id": "t2-108",
"type": "ranking",
"number": 108,
"name": "Ranking Match 108",
"field": 3,
"time": "2026-10-08T17:05:00.900+09:00",
"red": [
"POR",
"MAW",
"USA"
],
"blue": [
"TAN",
"UKR",
"IVB"
],
"played": true
},
{
"id": "t2-107",
"type": "ranking",
"number": 107,
"name": "Ranking Match 107",
"field": 5,
"time": "2026-10-08T17:05:00.900+09:00",
"red": [
"TGA",
"BIZ",
"HUN"
],
"blue": [
"YEM",
"SEY",
"MDV"
],
"played": true
},
{
"id": "t2-109",
"type": "ranking",
"number": 109,
"name": "Ranking Match 109",
"field": 1,
"time": "2026-10-08T17:13:00.900+09:00",
"red": [
"IND",
"SUD",
"ETH"
],
"blue": [
"GUA",
"SYR",
"BIH"
],
"played": true
},
{
"id": "t2-111",
"type": "ranking",
"number": 111,
"name": "Ranking Match 111",
"field": 3,
"time": "2026-10-08T17:13:00.900+09:00",
"red": [
"BOT",
"GRN",
"GBR"
],
"blue": [
"FIJ",
"HAI",
"VIE"
],
"played": true
},
{
"id": "t2-110",
"type": "ranking",
"number": 110,
"name": "Ranking Match 110",
"field": 4,
"time": "2026-10-08T17:13:00.900+09:00",
"red": [
"ERI",
"LAT",
"AFG"
],
"blue": [
"VEN",
"SVK",
"MGL"
],
"played": true
},
{
"id": "t2-112",
"type": "ranking",
"number": 112,
"name": "Ranking Match 112",
"field": 2,
"time": "2026-10-08T17:21:00.900+09:00",
"red": [
"FIN",
"CUB",
"ANG"
],
"blue": [
"MNE",
"GBS",
"RUS"
],
"played": true
},
{
"id": "t2-114",
"type": "ranking",
"number": 114,
"name": "Ranking Match 114",
"field": 3,
"time": "2026-10-08T17:21:00.900+09:00",
"red": [
"LBA",
"DMA",
"JPN"
],
"blue": [
"CAY",
"HON",
"JAM"
],
"played": true
},
{
"id": "t2-113",
"type": "ranking",
"number": 113,
"name": "Ranking Match 113",
"field": 5,
"time": "2026-10-08T17:21:00.900+09:00",
"red": [
"BHU",
"KOS",
"MDA"
],
"blue": [
"SRB",
"GAM",
"BEN"
],
"played": true
},
{
"id": "t2-115",
"type": "ranking",
"number": 115,
"name": "Ranking Match 115",
"field": 1,
"time": "2026-10-08T17:29:00.900+09:00",
"red": [
"BLR",
"PAN",
"KGZ"
],
"blue": [
"FRA",
"ESA",
"COD"
],
"played": true
},
{
"id": "t2-117",
"type": "ranking",
"number": 117,
"name": "Ranking Match 117",
"field": 3,
"time": "2026-10-08T17:29:00.900+09:00",
"red": [
"NED",
"TPE",
"NIG"
],
"blue": [
"LBR",
"GEQ",
"THA"
],
"played": true
},
{
"id": "t2-116",
"type": "ranking",
"number": 116,
"name": "Ranking Match 116",
"field": 4,
"time": "2026-10-08T17:29:00.900+09:00",
"red": [
"MYA",
"CIV",
"CPV"
],
"blue": [
"TTO",
"HPE",
"AUS"
],
"played": true
},
{
"id": "t2-118",
"type": "ranking",
"number": 118,
"name": "Ranking Match 118",
"field": 2,
"time": "2026-10-08T17:37:00.900+09:00",
"red": [
"CMR",
"LES",
"BUR"
],
"blue": [
"LCA",
"ARU",
"GEO"
],
"played": true
},
{
"id": "t2-120",
"type": "ranking",
"number": 120,
"name": "Ranking Match 120",
"field": 3,
"time": "2026-10-08T17:37:00.900+09:00",
"red": [
"UGA",
"VIN",
"TUR"
],
"blue": [
"PUR",
"BAR",
"MHL"
],
"played": true
},
{
"id": "t2-119",
"type": "ranking",
"number": 119,
"name": "Ranking Match 119",
"field": 5,
"time": "2026-10-08T17:37:00.900+09:00",
"red": [
"LTU",
"CGO",
"ZAM"
],
"blue": [
"VAN",
"KEN",
"MAD"
],
"played": true
},
{
"id": "t2-121",
"type": "ranking",
"number": 121,
"name": "Ranking Match 121",
"field": 1,
"time": "2026-10-09T09:15:00.900+09:00",
"red": [
"COK",
"MLI",
"POL"
],
"blue": [
"COL",
"QAT",
"DJI"
],
"played": true
},
{
"id": "t2-123",
"type": "ranking",
"number": 123,
"name": "Ranking Match 123",
"field": 3,
"time": "2026-10-09T09:15:00.900+09:00",
"red": [
"ECU",
"GAB",
"NGR"
],
"blue": [
"COM",
"TUN",
"CAM"
],
"played": true
},
{
"id": "t2-122",
"type": "ranking",
"number": 122,
"name": "Ranking Match 122",
"field": 4,
"time": "2026-10-09T09:15:00.900+09:00",
"red": [
"BEL",
"TKM",
"ALB"
],
"blue": [
"CRC",
"NAM",
"PAK"
],
"played": true
},
{
"id": "t2-124",
"type": "ranking",
"number": 124,
"name": "Ranking Match 124",
"field": 2,
"time": "2026-10-09T09:23:00.900+09:00",
"red": [
"ZIM",
"MKD",
"CRO"
],
"blue": [
"TOG",
"LBN",
"CAN"
],
"played": true
},
{
"id": "t2-126",
"type": "ranking",
"number": 126,
"name": "Ranking Match 126",
"field": 3,
"time": "2026-10-09T09:23:00.900+09:00",
"red": [
"MLT",
"GUI",
"RSA"
],
"blue": [
"CHA",
"BUL",
"PER"
],
"played": true
},
{
"id": "t2-125",
"type": "ranking",
"number": 125,
"name": "Ranking Match 125",
"field": 5,
"time": "2026-10-09T09:23:00.900+09:00",
"red": [
"MAR",
"LUX",
"IND"
],
"blue": [
"SRI",
"GUY",
"AZE"
],
"played": true
},
{
"id": "t2-127",
"type": "ranking",
"number": 127,
"name": "Ranking Match 127",
"field": 1,
"time": "2026-10-09T09:31:00.900+09:00",
"red": [
"IRL",
"FSM",
"MDV"
],
"blue": [
"BRU",
"USA",
"BOT"
],
"played": true
},
{
"id": "t2-129",
"type": "ranking",
"number": 129,
"name": "Ranking Match 129",
"field": 3,
"time": "2026-10-09T09:31:00.900+09:00",
"red": [
"GBS",
"AFG",
"GUA"
],
"blue": [
"SWZ",
"GBR",
"ALG"
],
"played": true
},
{
"id": "t2-128",
"type": "ranking",
"number": 128,
"name": "Ranking Match 128",
"field": 4,
"time": "2026-10-09T09:31:00.900+09:00",
"red": [
"IRI",
"SEY",
"FIJ"
],
"blue": [
"MAW",
"NEP",
"OMA"
],
"played": true
},
{
"id": "t2-130",
"type": "ranking",
"number": 130,
"name": "Ranking Match 130",
"field": 2,
"time": "2026-10-09T09:39:00.900+09:00",
"red": [
"HON",
"TJK",
"URU"
],
"blue": [
"ANG",
"MTN",
"YEM"
],
"played": true
},
{
"id": "t2-132",
"type": "ranking",
"number": 132,
"name": "Ranking Match 132",
"field": 3,
"time": "2026-10-09T09:39:00.900+09:00",
"red": [
"SLE",
"SOM",
"SLO"
],
"blue": [
"TAN",
"MOZ",
"MNE"
],
"played": true
},
{
"id": "t2-131",
"type": "ranking",
"number": 131,
"name": "Ranking Match 131",
"field": 5,
"time": "2026-10-09T09:39:00.900+09:00",
"red": [
"JPN",
"RUS",
"TGA"
],
"blue": [
"KOR",
"BIH",
"POR"
],
"played": true
},
{
"id": "t2-133",
"type": "ranking",
"number": 133,
"name": "Ranking Match 133",
"field": 1,
"time": "2026-10-09T09:47:00.900+09:00",
"red": [
"LBR",
"BAN",
"MAS"
],
"blue": [
"VIE",
"SWE",
"FIN"
],
"played": true
},
{
"id": "t2-135",
"type": "ranking",
"number": 135,
"name": "Ranking Match 135",
"field": 3,
"time": "2026-10-09T09:47:00.900+09:00",
"red": [
"CPV",
"EGY",
"STP"
],
"blue": [
"BLR",
"DEN",
"SVK"
],
"played": true
},
{
"id": "t2-134",
"type": "ranking",
"number": 134,
"name": "Ranking Match 134",
"field": 4,
"time": "2026-10-09T09:47:00.900+09:00",
"red": [
"MGL",
"PAN",
"NIG"
],
"blue": [
"BUR",
"CZE",
"ETH"
],
"played": true
},
{
"id": "t2-136",
"type": "ranking",
"number": 136,
"name": "Ranking Match 136",
"field": 2,
"time": "2026-10-09T09:55:00.900+09:00",
"red": [
"UAE",
"CHN",
"UGA"
],
"blue": [
"LAO",
"AUS",
"ESA"
],
"played": true
},
{
"id": "t2-138",
"type": "ranking",
"number": 138,
"name": "Ranking Match 138",
"field": 3,
"time": "2026-10-09T09:55:00.900+09:00",
"red": [
"PUR",
"VEN",
"TPE"
],
"blue": [
"ISR",
"CUB",
"CRC"
],
"played": true
},
{
"id": "t2-137",
"type": "ranking",
"number": 137,
"name": "Ranking Match 137",
"field": 5,
"time": "2026-10-09T09:55:00.900+09:00",
"red": [
"MHL",
"PAR",
"SOL"
],
"blue": [
"UKR",
"DJI",
"MYA"
],
"played": true
},
{
"id": "t2-139",
"type": "ranking",
"number": 139,
"name": "Ranking Match 139",
"field": 1,
"time": "2026-10-09T10:03:00.900+09:00",
"red": [
"MLI",
"LAT",
"IVB"
],
"blue": [
"ZAM",
"ISV",
"BEN"
],
"played": true
},
{
"id": "t2-141",
"type": "ranking",
"number": 141,
"name": "Ranking Match 141",
"field": 3,
"time": "2026-10-09T10:03:00.900+09:00",
"red": [
"PHI",
"ARG",
"LBA"
],
"blue": [
"MRI",
"CGO",
"COD"
],
"played": true
},
{
"id": "t2-140",
"type": "ranking",
"number": 140,
"name": "Ranking Match 140",
"field": 4,
"time": "2026-10-09T10:03:00.900+09:00",
"red": [
"ERI",
"KGZ",
"HPE"
],
"blue": [
"GHA",
"AUT",
"CAY"
],
"played": true
},
{
"id": "t2-142",
"type": "ranking",
"number": 142,
"name": "Ranking Match 142",
"field": 2,
"time": "2026-10-09T10:11:00.900+09:00",
"red": [
"KAZ",
"BHU",
"CMR"
],
"blue": [
"NCA",
"LTU",
"TUN"
],
"played": true
},
{
"id": "t2-144",
"type": "ranking",
"number": 144,
"name": "Ranking Match 144",
"field": 3,
"time": "2026-10-09T10:11:00.900+09:00",
"red": [
"EST",
"GRN",
"ESP"
],
"blue": [
"BIZ",
"NGR",
"LES"
],
"played": true
},
{
"id": "t2-143",
"type": "ranking",
"number": 143,
"name": "Ranking Match 143",
"field": 5,
"time": "2026-10-09T10:11:00.900+09:00",
"red": [
"ANT",
"JOR",
"MAD"
],
"blue": [
"GER",
"ARU",
"SEN"
],
"played": true
},
{
"id": "t2-145",
"type": "ranking",
"number": 145,
"name": "Ranking Match 145",
"field": 1,
"time": "2026-10-09T10:19:00.900+09:00",
"red": [
"CAF",
"INA",
"TKM"
],
"blue": [
"TTO",
"ZIM",
"BAR"
],
"played": true
},
{
"id": "t2-147",
"type": "ranking",
"number": 147,
"name": "Ranking Match 147",
"field": 3,
"time": "2026-10-09T10:19:00.900+09:00",
"red": [
"GUM",
"ITA",
"NAM"
],
"blue": [
"FRA",
"SRB",
"KIR"
],
"played": true
},
{
"id": "t2-146",
"type": "ranking",
"number": 146,
"name": "Ranking Match 146",
"field": 4,
"time": "2026-10-09T10:19:00.900+09:00",
"red": [
"HAI",
"GAM",
"VIN"
],
"blue": [
"BRA",
"THA",
"HUN"
],
"played": true
},
{
"id": "t2-148",
"type": "ranking",
"number": 148,
"name": "Ranking Match 148",
"field": 2,
"time": "2026-10-09T10:27:00.900+09:00",
"red": [
"DOM",
"ASA",
"SYR"
],
"blue": [
"IRQ",
"GAB",
"MEX"
],
"played": true
},
{
"id": "t2-150",
"type": "ranking",
"number": 150,
"name": "Ranking Match 150",
"field": 3,
"time": "2026-10-09T10:27:00.900+09:00",
"red": [
"MDA",
"ECU",
"NOR"
],
"blue": [
"DMA",
"QAT",
"RWA"
],
"played": true
},
{
"id": "t2-149",
"type": "ranking",
"number": 149,
"name": "Ranking Match 149",
"field": 5,
"time": "2026-10-09T10:27:00.900+09:00",
"red": [
"CHI",
"CAM",
"POL"
],
"blue": [
"PAK",
"LCA",
"SKN"
],
"played": true
},
{
"id": "t2-151",
"type": "ranking",
"number": 151,
"name": "Ranking Match 151",
"field": 1,
"time": "2026-10-09T10:35:00.900+09:00",
"red": [
"COL",
"COM",
"SUD"
],
"blue": [
"ROU",
"TLS",
"PNG"
],
"played": true
},
{
"id": "t2-153",
"type": "ranking",
"number": 153,
"name": "Ranking Match 153",
"field": 3,
"time": "2026-10-09T10:35:00.900+09:00",
"red": [
"TUR",
"BEL",
"COK"
],
"blue": [
"KEN",
"GEQ",
"BOL"
],
"played": true
},
{
"id": "t2-152",
"type": "ranking",
"number": 152,
"name": "Ranking Match 152",
"field": 4,
"time": "2026-10-09T10:35:00.900+09:00",
"red": [
"NED",
"GEO",
"VAN"
],
"blue": [
"HKG",
"ALB",
"JAM"
],
"played": true
},
{
"id": "t2-154",
"type": "ranking",
"number": 154,
"name": "Ranking Match 154",
"field": 2,
"time": "2026-10-09T10:43:00.900+09:00",
"red": [
"GRE",
"TOG",
"SSD"
],
"blue": [
"KOS",
"PLE",
"CIV"
],
"played": true
},
{
"id": "t2-156",
"type": "ranking",
"number": 156,
"name": "Ranking Match 156",
"field": 3,
"time": "2026-10-09T10:43:00.900+09:00",
"red": [
"AZE",
"BEN",
"CAY"
],
"blue": [
"LBN",
"LBR",
"IRL"
],
"played": true
},
{
"id": "t2-155",
"type": "ranking",
"number": 155,
"name": "Ranking Match 155",
"field": 5,
"time": "2026-10-09T10:43:00.900+09:00",
"red": [
"RUS",
"ZAM",
"DJI"
],
"blue": [
"MTN",
"CRO",
"UZB"
],
"played": true
},
{
"id": "t2-157",
"type": "ranking",
"number": 157,
"name": "Ranking Match 157",
"field": 1,
"time": "2026-10-09T10:51:00.900+09:00",
"red": [
"GBS",
"ESA",
"EGY"
],
"blue": [
"MAR",
"ISR",
"ISV"
],
"played": true
},
{
"id": "t2-159",
"type": "ranking",
"number": 159,
"name": "Ranking Match 159",
"field": 3,
"time": "2026-10-09T10:51:00.900+09:00",
"red": [
"MNE",
"TGA",
"ARU"
],
"blue": [
"USA",
"GBR",
"CZE"
],
"played": true
},
{
"id": "t2-158",
"type": "ranking",
"number": 158,
"name": "Ranking Match 158",
"field": 4,
"time": "2026-10-09T10:51:00.900+09:00",
"red": [
"BIH",
"KAZ",
"SVK"
],
"blue": [
"MOZ",
"FIN",
"UAE"
],
"played": true
},
{
"id": "t2-160",
"type": "ranking",
"number": 160,
"name": "Ranking Match 160",
"field": 2,
"time": "2026-10-09T11:10:00.900+09:00",
"red": [
"CRC",
"PAN",
"UGA"
],
"blue": [
"IRI",
"DEN",
"PER"
],
"played": true
},
{
"id": "t2-162",
"type": "ranking",
"number": 162,
"name": "Ranking Match 162",
"field": 3,
"time": "2026-10-09T11:10:00.900+09:00",
"red": [
"THA",
"IVB",
"SWZ"
],
"blue": [
"TKM",
"MGL",
"SLO"
],
"played": true
},
{
"id": "t2-161",
"type": "ranking",
"number": 161,
"name": "Ranking Match 161",
"field": 5,
"time": "2026-10-09T11:10:00.900+09:00",
"red": [
"CPV",
"BAN",
"JOR"
],
"blue": [
"SOL",
"IND",
"BUL"
],
"played": true
},
{
"id": "t2-163",
"type": "ranking",
"number": 163,
"name": "Ranking Match 163",
"field": 1,
"time": "2026-10-09T11:18:00.900+09:00",
"red": [
"TJK",
"LTU",
"FRA"
],
"blue": [
"MAS",
"BUR",
"VIN"
],
"played": true
},
{
"id": "t2-165",
"type": "ranking",
"number": 165,
"name": "Ranking Match 165",
"field": 3,
"time": "2026-10-09T11:18:00.900+09:00",
"red": [
"KGZ",
"ANG",
"TUN"
],
"blue": [
"CAF",
"OMA",
"JPN"
],
"played": true
},
{
"id": "t2-164",
"type": "ranking",
"number": 164,
"name": "Ranking Match 164",
"field": 4,
"time": "2026-10-09T11:18:00.900+09:00",
"red": [
"FSM",
"CAN",
"GER"
],
"blue": [
"MEX",
"SOM",
"ESP"
],
"played": true
},
{
"id": "t2-166",
"type": "ranking",
"number": 166,
"name": "Ranking Match 166",
"field": 2,
"time": "2026-10-09T11:26:00.900+09:00",
"red": [
"PAK",
"SYR",
"NEP"
],
"blue": [
"GAM",
"NGR",
"TPE"
],
"played": true
},
{
"id": "t2-168",
"type": "ranking",
"number": 168,
"name": "Ranking Match 168",
"field": 3,
"time": "2026-10-09T11:26:00.900+09:00",
"red": [
"AUT",
"ZIM",
"HKG"
],
"blue": [
"MAW",
"LES",
"NIG"
],
"played": true
},
{
"id": "t2-167",
"type": "ranking",
"number": 167,
"name": "Ranking Match 167",
"field": 5,
"time": "2026-10-09T11:26:00.900+09:00",
"red": [
"RSA",
"RWA",
"SRB"
],
"blue": [
"VIE",
"HUN",
"CHI"
],
"played": true
},
{
"id": "t2-169",
"type": "ranking",
"number": 169,
"name": "Ranking Match 169",
"field": 1,
"time": "2026-10-09T11:34:00.900+09:00",
"red": [
"MDV",
"MLI",
"BAR"
],
"blue": [
"HPE",
"ROU",
"GUI"
],
"played": true
},
{
"id": "t2-171",
"type": "ranking",
"number": 171,
"name": "Ranking Match 171",
"field": 3,
"time": "2026-10-09T11:34:00.900+09:00",
"red": [
"NED",
"ARG",
"EST"
],
"blue": [
"UZB",
"TAN",
"MYA"
],
"played": true
},
{
"id": "t2-170",
"type": "ranking",
"number": 170,
"name": "Ranking Match 170",
"field": 4,
"time": "2026-10-09T11:34:00.900+09:00",
"red": [
"NCA",
"SWE",
"JAM"
],
"blue": [
"KEN",
"GRE",
"DOM"
],
"played": true
},
{
"id": "t2-172",
"type": "ranking",
"number": 172,
"name": "Ranking Match 172",
"field": 2,
"time": "2026-10-09T11:42:00.900+09:00",
"red": [
"BHU",
"HON",
"QAT"
],
"blue": [
"ANT",
"TOG",
"PAR"
],
"played": true
},
{
"id": "t2-174",
"type": "ranking",
"number": 174,
"name": "Ranking Match 174",
"field": 3,
"time": "2026-10-09T11:42:00.900+09:00",
"red": [
"NAM",
"IRQ",
"LCA"
],
"blue": [
"BOL",
"ALG",
"SRI"
],
"played": true
},
{
"id": "t2-173",
"type": "ranking",
"number": 173,
"name": "Ranking Match 173",
"field": 5,
"time": "2026-10-09T11:42:00.900+09:00",
"red": [
"SEY",
"BOT",
"GAB"
],
"blue": [
"BEL",
"CIV",
"GUM"
],
"played": true
},
{
"id": "t2-175",
"type": "ranking",
"number": 175,
"name": "Ranking Match 175",
"field": 1,
"time": "2026-10-09T11:50:00.900+09:00",
"red": [
"BRU",
"SUD",
"CHN"
],
"blue": [
"HAI",
"SKN",
"DMA"
],
"played": true
},
{
"id": "t2-177",
"type": "ranking",
"number": 177,
"name": "Ranking Match 177",
"field": 3,
"time": "2026-10-09T11:50:00.900+09:00",
"red": [
"AUS",
"KOR",
"UKR"
],
"blue": [
"SEN",
"KOS",
"POL"
],
"played": true
},
{
"id": "t2-176",
"type": "ranking",
"number": 176,
"name": "Ranking Match 176",
"field": 4,
"time": "2026-10-09T11:50:00.900+09:00",
"red": [
"COL",
"PLE",
"GEQ"
],
"blue": [
"ECU",
"ITA",
"SLE"
],
"played": true
},
{
"id": "t2-178",
"type": "ranking",
"number": 178,
"name": "Ranking Match 178",
"field": 2,
"time": "2026-10-09T11:58:00.900+09:00",
"red": [
"GEO",
"LAT",
"LUX"
],
"blue": [
"LBA",
"CUB",
"TUR"
],
"played": true
},
{
"id": "t2-180",
"type": "ranking",
"number": 180,
"name": "Ranking Match 180",
"field": 3,
"time": "2026-10-09T11:58:00.900+09:00",
"red": [
"BRA",
"BIZ",
"NOR"
],
"blue": [
"MLT",
"BLR",
"COK"
],
"played": true
},
{
"id": "t2-179",
"type": "ranking",
"number": 179,
"name": "Ranking Match 179",
"field": 5,
"time": "2026-10-09T11:58:00.900+09:00",
"red": [
"MAD",
"TLS",
"TTO"
],
"blue": [
"ERI",
"LAO",
"MKD"
],
"played": true
},
{
"id": "t2-181",
"type": "ranking",
"number": 181,
"name": "Ranking Match 181",
"field": 1,
"time": "2026-10-09T12:06:00.900+09:00",
"red": [
"MHL",
"GUA",
"CGO"
],
"blue": [
"ASA",
"MDA",
"VEN"
],
"played": true
},
{
"id": "t2-183",
"type": "ranking",
"number": 183,
"name": "Ranking Match 183",
"field": 3,
"time": "2026-10-09T12:06:00.900+09:00",
"red": [
"COM",
"GRN",
"PHI"
],
"blue": [
"KIR",
"YEM",
"VAN"
],
"played": true
},
{
"id": "t2-182",
"type": "ranking",
"number": 182,
"name": "Ranking Match 182",
"field": 4,
"time": "2026-10-09T12:06:00.900+09:00",
"red": [
"ETH",
"GUY",
"PUR"
],
"blue": [
"SSD",
"ALB",
"URU"
],
"played": true
},
{
"id": "t2-184",
"type": "ranking",
"number": 184,
"name": "Ranking Match 184",
"field": 2,
"time": "2026-10-09T12:14:00.900+09:00",
"red": [
"COD",
"POR",
"CAM"
],
"blue": [
"STP",
"INA",
"FIJ"
],
"played": true
},
{
"id": "t2-186",
"type": "ranking",
"number": 186,
"name": "Ranking Match 186",
"field": 3,
"time": "2026-10-09T12:14:00.900+09:00",
"red": [
"MEX",
"CHI",
"UGA"
],
"blue": [
"BAN",
"ISR",
"ANG"
],
"played": true
},
{
"id": "t2-185",
"type": "ranking",
"number": 185,
"name": "Ranking Match 185",
"field": 5,
"time": "2026-10-09T12:14:00.900+09:00",
"red": [
"GHA",
"MRI",
"CHA"
],
"blue": [
"PNG",
"AFG",
"CMR"
],
"played": true
},
{
"id": "t2-187",
"type": "ranking",
"number": 187,
"name": "Ranking Match 187",
"field": 1,
"time": "2026-10-09T12:22:00.900+09:00",
"red": [
"SYR",
"GUI",
"NCA"
],
"blue": [
"MYA",
"JPN",
"GBS"
],
"played": true
},
{
"id": "t2-189",
"type": "ranking",
"number": 189,
"name": "Ranking Match 189",
"field": 3,
"time": "2026-10-09T12:22:00.900+09:00",
"red": [
"IND",
"VIE",
"KAZ"
],
"blue": [
"PAN",
"GRE",
"EGY"
],
"played": true
},
{
"id": "t2-188",
"type": "ranking",
"number": 188,
"name": "Ranking Match 188",
"field": 4,
"time": "2026-10-09T12:22:00.900+09:00",
"red": [
"GBR",
"TJK",
"IRI"
],
"blue": [
"CAF",
"LBR",
"MDV"
],
"played": true
},
{
"id": "t2-190",
"type": "ranking",
"number": 190,
"name": "Ranking Match 190",
"field": 2,
"time": "2026-10-09T12:30:00.900+09:00",
"red": [
"PER",
"RUS",
"TAN"
],
"blue": [
"HPE",
"BOT",
"AZE"
],
"played": true
},
{
"id": "t2-192",
"type": "ranking",
"number": 192,
"name": "Ranking Match 192",
"field": 3,
"time": "2026-10-09T12:30:00.900+09:00",
"red": [
"ARU",
"ISV",
"SKN"
],
"blue": [
"NAM",
"BHU",
"FSM"
],
"played": true
},
{
"id": "t2-191",
"type": "ranking",
"number": 191,
"name": "Ranking Match 191",
"field": 5,
"time": "2026-10-09T12:30:00.900+09:00",
"red": [
"LCA",
"CHN",
"UZB"
],
"blue": [
"CZE",
"NGR",
"SEY"
],
"played": true
},
{
"id": "t2-193",
"type": "ranking",
"number": 193,
"name": "Ranking Match 193",
"field": 1,
"time": "2026-10-09T12:38:00.900+09:00",
"red": [
"BUL",
"OMA",
"RWA"
],
"blue": [
"SEN",
"CAY",
"UAE"
],
"played": true
},
{
"id": "t2-195",
"type": "ranking",
"number": 195,
"name": "Ranking Match 195",
"field": 3,
"time": "2026-10-09T12:38:00.900+09:00",
"red": [
"BEN",
"MTN",
"SRI"
],
"blue": [
"TOG",
"HKG",
"SUD"
],
"played": true
},
{
"id": "t2-194",
"type": "ranking",
"number": 194,
"name": "Ranking Match 194",
"field": 4,
"time": "2026-10-09T12:38:00.900+09:00",
"red": [
"ECU",
"ZAM",
"PAR"
],
"blue": [
"MAS",
"GER",
"ESA"
],
"played": true
},
{
"id": "t2-196",
"type": "ranking",
"number": 196,
"name": "Ranking Match 196",
"field": 2,
"time": "2026-10-09T12:46:00.900+09:00",
"red": [
"BRA",
"KOR",
"JAM"
],
"blue": [
"BRU",
"RSA",
"GAB"
],
"played": true
},
{
"id": "t2-198",
"type": "ranking",
"number": 198,
"name": "Ranking Match 198",
"field": 3,
"time": "2026-10-09T12:46:00.900+09:00",
"red": [
"VIN",
"PAK",
"ASA"
],
"blue": [
"SWZ",
"ETH",
"LAT"
],
"played": true
},
{
"id": "t2-197",
"type": "ranking",
"number": 197,
"name": "Ranking Match 197",
"field": 5,
"time": "2026-10-09T12:46:00.900+09:00",
"red": [
"PLE",
"UKR",
"FIN"
],
"blue": [
"SRB",
"ARG",
"TPE"
],
"played": true
},
{
"id": "t2-199",
"type": "ranking",
"number": 199,
"name": "Ranking Match 199",
"field": 1,
"time": "2026-10-09T12:54:00.900+09:00",
"red": [
"CUB",
"CAN",
"MDA"
],
"blue": [
"LAO",
"MLI",
"BIZ"
],
"played": true
},
{
"id": "t2-201",
"type": "ranking",
"number": 201,
"name": "Ranking Match 201",
"field": 3,
"time": "2026-10-09T12:54:00.900+09:00",
"red": [
"COD",
"TUN",
"ZIM"
],
"blue": [
"SLO",
"SOL",
"DEN"
],
"played": true
},
{
"id": "t2-200",
"type": "ranking",
"number": 200,
"name": "Ranking Match 200",
"field": 4,
"time": "2026-10-09T12:54:00.900+09:00",
"red": [
"KOS",
"DOM",
"NED"
],
"blue": [
"ITA",
"BUR",
"GRN"
],
"played": true
},
{
"id": "t2-202",
"type": "ranking",
"number": 202,
"name": "Ranking Match 202",
"field": 2,
"time": "2026-10-09T14:00:00.900+09:00",
"red": [
"VEN",
"STP",
"LES"
],
"blue": [
"DJI",
"MLT",
"URU"
],
"played": true
},
{
"id": "t2-204",
"type": "ranking",
"number": 204,
"name": "Ranking Match 204",
"field": 3,
"time": "2026-10-09T14:00:00.900+09:00",
"red": [
"USA",
"COM",
"NEP"
],
"blue": [
"CMR",
"MAD",
"PUR"
],
"played": true
},
{
"id": "t2-203",
"type": "ranking",
"number": 203,
"name": "Ranking Match 203",
"field": 5,
"time": "2026-10-09T14:00:00.900+09:00",
"red": [
"ESP",
"SWE",
"CRC"
],
"blue": [
"MKD",
"CPV",
"MGL"
],
"played": true
},
{
"id": "t2-205",
"type": "ranking",
"number": 205,
"name": "Ranking Match 205",
"field": 1,
"time": "2026-10-09T14:08:00.900+09:00",
"red": [
"TGA",
"COK",
"GUM"
],
"blue": [
"KGZ",
"IRL",
"JOR"
],
"played": true
},
{
"id": "t2-207",
"type": "ranking",
"number": 207,
"name": "Ranking Match 207",
"field": 3,
"time": "2026-10-09T14:08:00.900+09:00",
"red": [
"CHA",
"POR",
"QAT"
],
"blue": [
"SOM",
"ALG",
"TUR"
],
"played": true
},
{
"id": "t2-206",
"type": "ranking",
"number": 206,
"name": "Ranking Match 206",
"field": 4,
"time": "2026-10-09T14:08:00.900+09:00",
"red": [
"BOL",
"KIR",
"ERI"
],
"blue": [
"CAM",
"TKM",
"SSD"
],
"played": true
},
{
"id": "t2-208",
"type": "ranking",
"number": 208,
"name": "Ranking Match 208",
"field": 2,
"time": "2026-10-09T14:16:00.900+09:00",
"red": [
"LTU",
"EST",
"GUY"
],
"blue": [
"GAM",
"SLE",
"LBA"
],
"played": true
},
{
"id": "t2-210",
"type": "ranking",
"number": 210,
"name": "Ranking Match 210",
"field": 3,
"time": "2026-10-09T14:16:00.900+09:00",
"red": [
"BLR",
"INA",
"GHA"
],
"blue": [
"CIV",
"COL",
"MOZ"
],
"played": true
},
{
"id": "t2-209",
"type": "ranking",
"number": 209,
"name": "Ranking Match 209",
"field": 5,
"time": "2026-10-09T14:16:00.900+09:00",
"red": [
"THA",
"GUA",
"HON"
],
"blue": [
"FIJ",
"BAR",
"PNG"
],
"played": true
},
{
"id": "t2-211",
"type": "ranking",
"number": 211,
"name": "Ranking Match 211",
"field": 1,
"time": "2026-10-09T14:24:00.900+09:00",
"red": [
"HUN",
"MNE",
"LBN"
],
"blue": [
"VAN",
"MHL",
"MRI"
],
"played": true
},
{
"id": "t2-213",
"type": "ranking",
"number": 213,
"name": "Ranking Match 213",
"field": 3,
"time": "2026-10-09T14:24:00.900+09:00",
"red": [
"CRO",
"KEN",
"LUX"
],
"blue": [
"ALB",
"MAW",
"ROU"
],
"played": true
},
{
"id": "t2-212",
"type": "ranking",
"number": 212,
"name": "Ranking Match 212",
"field": 4,
"time": "2026-10-09T14:24:00.900+09:00",
"red": [
"TLS",
"NIG",
"FRA"
],
"blue": [
"PHI",
"HAI",
"SVK"
],
"played": true
},
{
"id": "t2-214",
"type": "ranking",
"number": 214,
"name": "Ranking Match 214",
"field": 2,
"time": "2026-10-09T14:32:00.900+09:00",
"red": [
"AFG",
"DMA",
"GEO"
],
"blue": [
"IVB",
"MAR",
"BIH"
],
"played": true
},
{
"id": "t2-216",
"type": "ranking",
"number": 216,
"name": "Ranking Match 216",
"field": 3,
"time": "2026-10-09T14:32:00.900+09:00",
"red": [
"IRQ",
"POL",
"BEL"
],
"blue": [
"AUT",
"TTO",
"VIN"
],
"played": true
},
{
"id": "t2-215",
"type": "ranking",
"number": 215,
"name": "Ranking Match 215",
"field": 5,
"time": "2026-10-09T14:32:00.900+09:00",
"red": [
"AUS",
"CGO",
"YEM"
],
"blue": [
"GEQ",
"NOR",
"ANT"
],
"played": true
},
{
"id": "t2-217",
"type": "ranking",
"number": 217,
"name": "Ranking Match 217",
"field": 1,
"time": "2026-10-09T14:40:00.900+09:00",
"red": [
"SRB",
"BIZ",
"MAS"
],
"blue": [
"BOT",
"CHN",
"GBS"
],
"played": true
},
{
"id": "t2-219",
"type": "ranking",
"number": 219,
"name": "Ranking Match 219",
"field": 3,
"time": "2026-10-09T14:40:00.900+09:00",
"red": [
"GUI",
"SEN",
"SLO"
],
"blue": [
"FIN",
"FSM",
"ASA"
],
"played": true
},
{
"id": "t2-218",
"type": "ranking",
"number": 218,
"name": "Ranking Match 218",
"field": 4,
"time": "2026-10-09T14:40:00.900+09:00",
"red": [
"GAB",
"BAN",
"CAF"
],
"blue": [
"MDA",
"NCA",
"CAY"
],
"played": true
},
{
"id": "t2-220",
"type": "ranking",
"number": 220,
"name": "Ranking Match 220",
"field": 2,
"time": "2026-10-09T14:48:00.900+09:00",
"red": [
"COM",
"BRU",
"TOG"
],
"blue": [
"UAE",
"ISR",
"STP"
],
"played": true
},
{
"id": "t2-222",
"type": "ranking",
"number": 222,
"name": "Ranking Match 222",
"field": 3,
"time": "2026-10-09T14:48:00.900+09:00",
"red": [
"ZAM",
"MEX",
"JOR"
],
"blue": [
"SWZ",
"BOL",
"IRI"
],
"played": true
},
{
"id": "t2-221",
"type": "ranking",
"number": 221,
"name": "Ranking Match 221",
"field": 5,
"time": "2026-10-09T14:48:00.900+09:00",
"red": [
"CPV",
"CZE",
"RSA"
],
"blue": [
"BHU",
"NEP",
"DOM"
],
"played": true
},
{
"id": "t2-223",
"type": "ranking",
"number": 223,
"name": "Ranking Match 223",
"field": 1,
"time": "2026-10-09T14:56:00.900+09:00",
"red": [
"SWE",
"BRA",
"MDV"
],
"blue": [
"POR",
"EGY",
"BUR"
],
"played": true
},
{
"id": "t2-225",
"type": "ranking",
"number": 225,
"name": "Ranking Match 225",
"field": 3,
"time": "2026-10-09T14:56:00.900+09:00",
"red": [
"BEN",
"KOR",
"CUB"
],
"blue": [
"TUN",
"MLT",
"GUY"
],
"played": true
},
{
"id": "t2-224",
"type": "ranking",
"number": 224,
"name": "Ranking Match 224",
"field": 4,
"time": "2026-10-09T14:56:00.900+09:00",
"red": [
"SEY",
"DJI",
"GRE"
],
"blue": [
"PER",
"JPN",
"ECU"
],
"played": true
},
{
"id": "t2-226",
"type": "ranking",
"number": 226,
"name": "Ranking Match 226",
"field": 2,
"time": "2026-10-09T15:04:00.900+09:00",
"red": [
"ZIM",
"SKN",
"TPE"
],
"blue": [
"SRI",
"TUR",
"MLI"
],
"played": true
},
{
"id": "t2-228",
"type": "ranking",
"number": 228,
"name": "Ranking Match 228",
"field": 3,
"time": "2026-10-09T15:04:00.900+09:00",
"red": [
"HKG",
"SSD",
"LBN"
],
"blue": [
"SVK",
"PAN",
"NAM"
],
"played": true
},
{
"id": "t2-227",
"type": "ranking",
"number": 227,
"name": "Ranking Match 227",
"field": 5,
"time": "2026-10-09T15:04:00.900+09:00",
"red": [
"GRN",
"DEN",
"MYA"
],
"blue": [
"LCA",
"SUD",
"TJK"
],
"played": true
},
{
"id": "t2-229",
"type": "ranking",
"number": 229,
"name": "Ranking Match 229",
"field": 1,
"time": "2026-10-09T15:12:00.900+09:00",
"red": [
"HPE",
"PLE",
"KEN"
],
"blue": [
"TKM",
"SOL",
"TGA"
],
"played": true
},
{
"id": "t2-231",
"type": "ranking",
"number": 231,
"name": "Ranking Match 231",
"field": 3,
"time": "2026-10-09T15:12:00.900+09:00",
"red": [
"ESP",
"VIE",
"BIH"
],
"blue": [
"OMA",
"COD",
"VAN"
],
"played": true
},
{
"id": "t2-230",
"type": "ranking",
"number": 230,
"name": "Ranking Match 230",
"field": 4,
"time": "2026-10-09T15:12:00.900+09:00",
"red": [
"ALB",
"RUS",
"MGL"
],
"blue": [
"ARU",
"UGA",
"SYR"
],
"played": true
},
{
"id": "t2-232",
"type": "ranking",
"number": 232,
"name": "Ranking Match 232",
"field": 2,
"time": "2026-10-09T15:30:00.900+09:00",
"red": [
"JAM",
"KGZ",
"CAN"
],
"blue": [
"LUX",
"POL",
"SLE"
],
"played": true
},
{
"id": "t2-234",
"type": "ranking",
"number": 234,
"name": "Ranking Match 234",
"field": 3,
"time": "2026-10-09T15:30:00.900+09:00",
"red": [
"LBR",
"PHI",
"VEN"
],
"blue": [
"ITA",
"CMR",
"CRO"
],
"played": true
},
{
"id": "t2-233",
"type": "ranking",
"number": 233,
"name": "Ranking Match 233",
"field": 5,
"time": "2026-10-09T15:30:00.900+09:00",
"red": [
"AUT",
"RWA",
"CGO"
],
"blue": [
"INA",
"ETH",
"CRC"
],
"played": true
},
{
"id": "t2-235",
"type": "ranking",
"number": 235,
"name": "Ranking Match 235",
"field": 1,
"time": "2026-10-09T15:38:00.900+09:00",
"red": [
"THA",
"ALG",
"GEO"
],
"blue": [
"ERI",
"URU",
"FRA"
],
"played": true
},
{
"id": "t2-237",
"type": "ranking",
"number": 237,
"name": "Ranking Match 237",
"field": 3,
"time": "2026-10-09T15:38:00.900+09:00",
"red": [
"MNE",
"CIV",
"ARG"
],
"blue": [
"MKD",
"PNG",
"NGR"
],
"played": true
},
{
"id": "t2-236",
"type": "ranking",
"number": 236,
"name": "Ranking Match 236",
"field": 4,
"time": "2026-10-09T15:38:00.900+09:00",
"red": [
"PUR",
"NED",
"KAZ"
],
"blue": [
"GAM",
"HON",
"CAM"
],
"played": true
},
{
"id": "t2-238",
"type": "ranking",
"number": 238,
"name": "Ranking Match 238",
"field": 2,
"time": "2026-10-09T15:46:00.900+09:00",
"red": [
"ANG",
"BUL",
"MAW"
],
"blue": [
"MRI",
"ANT",
"MAR"
],
"played": true
},
{
"id": "t2-240",
"type": "ranking",
"number": 240,
"name": "Ranking Match 240",
"field": 3,
"time": "2026-10-09T15:46:00.900+09:00",
"red": [
"NIG",
"FIJ",
"GER"
],
"blue": [
"CHA",
"NOR",
"HUN"
],
"played": true
},
{
"id": "t2-239",
"type": "ranking",
"number": 239,
"name": "Ranking Match 239",
"field": 5,
"time": "2026-10-09T15:46:00.900+09:00",
"red": [
"DMA",
"CHI",
"IRQ"
],
"blue": [
"UKR",
"BAR",
"TLS"
],
"played": true
},
{
"id": "t2-241",
"type": "ranking",
"number": 241,
"name": "Ranking Match 241",
"field": 1,
"time": "2026-10-09T15:54:00.900+09:00",
"red": [
"ESA",
"LBA",
"USA"
],
"blue": [
"KOS",
"AFG",
"AZE"
],
"played": true
},
{
"id": "t2-243",
"type": "ranking",
"number": 243,
"name": "Ranking Match 243",
"field": 3,
"time": "2026-10-09T15:54:00.900+09:00",
"red": [
"MAD",
"COL",
"PAK"
],
"blue": [
"YEM",
"GUM",
"PAR"
],
"played": true
},
{
"id": "t2-242",
"type": "ranking",
"number": 242,
"name": "Ranking Match 242",
"field": 4,
"time": "2026-10-09T15:54:00.900+09:00",
"red": [
"IVB",
"GUA",
"BEL"
],
"blue": [
"LTU",
"LES",
"MOZ"
],
"played": true
},
{
"id": "t2-244",
"type": "ranking",
"number": 244,
"name": "Ranking Match 244",
"field": 2,
"time": "2026-10-09T16:02:00.900+09:00",
"red": [
"MHL",
"EST",
"BLR"
],
"blue": [
"ISV",
"GEQ",
"HAI"
],
"played": true
},
{
"id": "t2-246",
"type": "ranking",
"number": 246,
"name": "Ranking Match 246",
"field": 3,
"time": "2026-10-09T16:02:00.900+09:00",
"red": [
"ROU",
"SOM",
"AUS"
],
"blue": [
"UZB",
"IND",
"LAT"
],
"played": true
},
{
"id": "t2-245",
"type": "ranking",
"number": 245,
"name": "Ranking Match 245",
"field": 5,
"time": "2026-10-09T16:02:00.900+09:00",
"red": [
"LAO",
"IRL",
"KIR"
],
"blue": [
"QAT",
"TAN",
"GHA"
],
"played": true
},
{
"id": "t2-247",
"type": "ranking",
"number": 247,
"name": "Ranking Match 247",
"field": 1,
"time": "2026-10-09T16:10:00.900+09:00",
"red": [
"SEY",
"TTO",
"COK"
],
"blue": [
"CAY",
"GBR",
"MTN"
],
"played": true
},
{
"id": "t2-249",
"type": "ranking",
"number": 249,
"name": "Ranking Match 249",
"field": 3,
"time": "2026-10-09T16:10:00.900+09:00",
"red": [
"CGO",
"CAF",
"PAN"
],
"blue": [
"BOT",
"CPV",
"TOG"
],
"played": true
},
{
"id": "t2-248",
"type": "ranking",
"number": 248,
"name": "Ranking Match 248",
"field": 4,
"time": "2026-10-09T16:10:00.900+09:00",
"red": [
"VAN",
"TKM",
"FSM"
],
"blue": [
"DOM",
"GUY",
"BAN"
],
"played": true
},
{
"id": "t2-250",
"type": "ranking",
"number": 250,
"name": "Ranking Match 250",
"field": 2,
"time": "2026-10-09T16:18:00.900+09:00",
"red": [
"ITA",
"PER",
"CZE"
],
"blue": [
"GBS",
"TJK",
"MDA"
],
"played": true
},
{
"id": "t2-252",
"type": "ranking",
"number": 252,
"name": "Ranking Match 252",
"field": 3,
"time": "2026-10-09T16:18:00.900+09:00",
"red": [
"JOR",
"SVK",
"BRU"
],
"blue": [
"GUI",
"POL",
"CUB"
],
"played": true
},
{
"id": "t2-251",
"type": "ranking",
"number": 251,
"name": "Ranking Match 251",
"field": 5,
"time": "2026-10-09T16:18:00.900+09:00",
"red": [
"THA",
"SRB",
"SOL"
],
"blue": [
"JAM",
"ASA",
"BOL"
],
"played": true
},
{
"id": "t2-253",
"type": "ranking",
"number": 253,
"name": "Ranking Match 253",
"field": 1,
"time": "2026-10-09T16:26:00.900+09:00",
"red": [
"GRE",
"PNG",
"KOR"
],
"blue": [
"SLO",
"URU",
"GAM"
],
"played": true
},
{
"id": "t2-255",
"type": "ranking",
"number": 255,
"name": "Ranking Match 255",
"field": 3,
"time": "2026-10-09T16:26:00.900+09:00",
"red": [
"PLE",
"PUR",
"MNE"
],
"blue": [
"ALG",
"CHN",
"MLI"
],
"played": true
},
{
"id": "t2-254",
"type": "ranking",
"number": 254,
"name": "Ranking Match 254",
"field": 4,
"time": "2026-10-09T16:26:00.900+09:00",
"red": [
"BUL",
"BIH",
"SKN"
],
"blue": [
"BEN",
"BUR",
"STP"
],
"played": true
},
{
"id": "t2-256",
"type": "ranking",
"number": 256,
"name": "Ranking Match 256",
"field": 2,
"time": "2026-10-09T16:34:00.900+09:00",
"red": [
"DMA",
"MRI",
"TGA"
],
"blue": [
"SEN",
"MLT",
"AUT"
],
"played": true
},
{
"id": "t2-258",
"type": "ranking",
"number": 258,
"name": "Ranking Match 258",
"field": 3,
"time": "2026-10-09T16:34:00.900+09:00",
"red": [
"LES",
"RWA",
"LBN"
],
"blue": [
"DEN",
"ALB",
"KOS"
],
"played": true
},
{
"id": "t2-257",
"type": "ranking",
"number": 257,
"name": "Ranking Match 257",
"field": 5,
"time": "2026-10-09T16:34:00.900+09:00",
"red": [
"OMA",
"NCA",
"ESA"
],
"blue": [
"MDV",
"COM",
"UKR"
],
"played": true
},
{
"id": "t2-259",
"type": "ranking",
"number": 259,
"name": "Ranking Match 259",
"field": 1,
"time": "2026-10-09T16:42:00.900+09:00",
"red": [
"ANT",
"AZE",
"CHA"
],
"blue": [
"CHI",
"MOZ",
"SUD"
],
"played": true
},
{
"id": "t2-261",
"type": "ranking",
"number": 261,
"name": "Ranking Match 261",
"field": 3,
"time": "2026-10-09T16:42:00.900+09:00",
"red": [
"HPE",
"MGL",
"COL"
],
"blue": [
"RSA",
"HAI",
"SSD"
],
"played": true
},
{
"id": "t2-260",
"type": "ranking",
"number": 260,
"name": "Ranking Match 260",
"field": 4,
"time": "2026-10-09T16:42:00.900+09:00",
"red": [
"INA",
"ECU",
"KEN"
],
"blue": [
"USA",
"SWZ",
"RUS"
],
"played": true
},
{
"id": "t2-262",
"type": "ranking",
"number": 262,
"name": "Ranking Match 262",
"field": 2,
"time": "2026-10-09T16:50:00.900+09:00",
"red": [
"ROU",
"PAR",
"GEQ"
],
"blue": [
"GAB",
"IVB",
"ERI"
],
"played": true
},
{
"id": "t2-264",
"type": "ranking",
"number": 264,
"name": "Ranking Match 264",
"field": 3,
"time": "2026-10-09T16:50:00.900+09:00",
"red": [
"TLS",
"SYR",
"LBA"
],
"blue": [
"VEN",
"ESP",
"EGY"
],
"played": true
},
{
"id": "t2-263",
"type": "ranking",
"number": 263,
"name": "Ranking Match 263",
"field": 5,
"time": "2026-10-09T16:50:00.900+09:00",
"red": [
"NAM",
"IRI",
"VIE"
],
"blue": [
"TTO",
"EST",
"SOM"
],
"played": true
},
{
"id": "t2-265",
"type": "ranking",
"number": 265,
"name": "Ranking Match 265",
"field": 1,
"time": "2026-10-09T16:58:00.900+09:00",
"red": [
"PHI",
"PAK",
"FIJ"
],
"blue": [
"AFG",
"ZAM",
"KGZ"
],
"played": true
},
{
"id": "t2-267",
"type": "ranking",
"number": 267,
"name": "Ranking Match 267",
"field": 3,
"time": "2026-10-09T16:58:00.900+09:00",
"red": [
"MEX",
"BEL",
"BIZ"
],
"blue": [
"SWE",
"ZIM",
"GHA"
],
"played": true
},
{
"id": "t2-266",
"type": "ranking",
"number": 266,
"name": "Ranking Match 266",
"field": 4,
"time": "2026-10-09T16:58:00.900+09:00",
"red": [
"MYA",
"BLR",
"ISR"
],
"blue": [
"HON",
"CMR",
"LAO"
],
"played": true
},
{
"id": "t2-268",
"type": "ranking",
"number": 268,
"name": "Ranking Match 268",
"field": 2,
"time": "2026-10-10T09:15:00.900+09:00",
"red": [
"CRC",
"SLE",
"NED"
],
"blue": [
"TUR",
"ISV",
"YEM"
],
"played": true
},
{
"id": "t2-270",
"type": "ranking",
"number": 270,
"name": "Ranking Match 270",
"field": 3,
"time": "2026-10-10T09:15:00.900+09:00",
"red": [
"NIG",
"UZB",
"SRI"
],
"blue": [
"MHL",
"CAN",
"GRN"
],
"played": true
},
{
"id": "t2-269",
"type": "ranking",
"number": 269,
"name": "Ranking Match 269",
"field": 5,
"time": "2026-10-10T09:15:00.900+09:00",
"red": [
"TAN",
"LBR",
"LTU"
],
"blue": [
"IND",
"NOR",
"GEO"
],
"played": true
},
{
"id": "t2-271",
"type": "ranking",
"number": 271,
"name": "Ranking Match 271",
"field": 1,
"time": "2026-10-10T09:23:00.900+09:00",
"red": [
"CAM",
"MAR",
"MKD"
],
"blue": [
"GUM",
"UGA",
"JPN"
],
"played": true
},
{
"id": "t2-273",
"type": "ranking",
"number": 273,
"name": "Ranking Match 273",
"field": 3,
"time": "2026-10-10T09:23:00.900+09:00",
"red": [
"MTN",
"NGR",
"COD"
],
"blue": [
"QAT",
"KAZ",
"VIN"
],
"played": true
},
{
"id": "t2-272",
"type": "ranking",
"number": 272,
"name": "Ranking Match 272",
"field": 4,
"time": "2026-10-10T09:23:00.900+09:00",
"red": [
"GER",
"CIV",
"LUX"
],
"blue": [
"COK",
"NEP",
"LCA"
],
"played": true
},
{
"id": "t2-274",
"type": "ranking",
"number": 274,
"name": "Ranking Match 274",
"field": 2,
"time": "2026-10-10T09:31:00.900+09:00",
"red": [
"TUN",
"MAD",
"LAT"
],
"blue": [
"ARG",
"IRQ",
"HUN"
],
"played": true
},
{
"id": "t2-276",
"type": "ranking",
"number": 276,
"name": "Ranking Match 276",
"field": 3,
"time": "2026-10-10T09:31:00.900+09:00",
"red": [
"BAR",
"AUS",
"BRA"
],
"blue": [
"FIN",
"KIR",
"MAW"
],
"played": true
},
{
"id": "t2-275",
"type": "ranking",
"number": 275,
"name": "Ranking Match 275",
"field": 5,
"time": "2026-10-10T09:31:00.900+09:00",
"red": [
"POR",
"DJI",
"ETH"
],
"blue": [
"GBR",
"MAS",
"BHU"
],
"played": true
},
{
"id": "t2-277",
"type": "ranking",
"number": 277,
"name": "Ranking Match 277",
"field": 1,
"time": "2026-10-10T09:39:00.900+09:00",
"red": [
"GUA",
"UAE",
"ARU"
],
"blue": [
"FRA",
"IRL",
"HKG"
],
"played": true
},
{
"id": "t2-279",
"type": "ranking",
"number": 279,
"name": "Ranking Match 279",
"field": 3,
"time": "2026-10-10T09:39:00.900+09:00",
"red": [
"LES",
"SLO",
"IRI"
],
"blue": [
"PLE",
"ERI",
"CPV"
],
"played": true
},
{
"id": "t2-278",
"type": "ranking",
"number": 278,
"name": "Ranking Match 278",
"field": 4,
"time": "2026-10-10T09:39:00.900+09:00",
"red": [
"ANG",
"TPE",
"DEN"
],
"blue": [
"CRO",
"BUR",
"COM"
],
"played": true
},
{
"id": "t2-280",
"type": "ranking",
"number": 280,
"name": "Ranking Match 280",
"field": 2,
"time": "2026-10-10T09:47:00.900+09:00",
"red": [
"SEN",
"KEN",
"PAN"
],
"blue": [
"TJK",
"CHA",
"CHN"
],
"played": true
},
{
"id": "t2-282",
"type": "ranking",
"number": 282,
"name": "Ranking Match 282",
"field": 3,
"time": "2026-10-10T09:47:00.900+09:00",
"red": [
"ANT",
"SEY",
"BIH"
],
"blue": [
"RWA",
"PNG",
"BOL"
],
"played": true
},
{
"id": "t2-281",
"type": "ranking",
"number": 281,
"name": "Ranking Match 281",
"field": 5,
"time": "2026-10-10T09:47:00.900+09:00",
"red": [
"OMA",
"BEN",
"HPE"
],
"blue": [
"GRE",
"USA",
"DMA"
],
"played": true
},
{
"id": "t2-283",
"type": "ranking",
"number": 283,
"name": "Ranking Match 283",
"field": 1,
"time": "2026-10-10T09:55:00.900+09:00",
"red": [
"ESA",
"GAM",
"ALG"
],
"blue": [
"CUB",
"MYA",
"INA"
],
"played": true
},
{
"id": "t2-285",
"type": "ranking",
"number": 285,
"name": "Ranking Match 285",
"field": 3,
"time": "2026-10-10T09:55:00.900+09:00",
"red": [
"MOZ",
"KOS",
"SWE"
],
"blue": [
"GUY",
"MRI",
"ASA"
],
"played": true
},
{
"id": "t2-284",
"type": "ranking",
"number": 284,
"name": "Ranking Match 284",
"field": 4,
"time": "2026-10-10T09:55:00.900+09:00",
"red": [
"ECU",
"NCA",
"PHI"
],
"blue": [
"SKN",
"CRC",
"SRB"
],
"played": true
},
{
"id": "t2-286",
"type": "ranking",
"number": 286,
"name": "Ranking Match 286",
"field": 2,
"time": "2026-10-10T10:03:00.900+09:00",
"red": [
"SWZ",
"FIJ",
"GAB"
],
"blue": [
"ALB",
"ESP",
"TTO"
],
"played": true
},
{
"id": "t2-288",
"type": "ranking",
"number": 288,
"name": "Ranking Match 288",
"field": 3,
"time": "2026-10-10T10:03:00.900+09:00",
"red": [
"SLE",
"BRU",
"BAN"
],
"blue": [
"RUS",
"BLR",
"LBN"
],
"played": true
},
{
"id": "t2-287",
"type": "ranking",
"number": 287,
"name": "Ranking Match 287",
"field": 5,
"time": "2026-10-10T10:03:00.900+09:00",
"red": [
"VIE",
"MNE",
"ISR"
],
"blue": [
"SUD",
"MGL",
"KOR"
],
"played": true
},
{
"id": "t2-289",
"type": "ranking",
"number": 289,
"name": "Ranking Match 289",
"field": 1,
"time": "2026-10-10T10:11:00.900+09:00",
"red": [
"CAY",
"MAR",
"CMR"
],
"blue": [
"TOG",
"TLS",
"TKM"
],
"played": true
},
{
"id": "t2-291",
"type": "ranking",
"number": 291,
"name": "Ranking Match 291",
"field": 3,
"time": "2026-10-10T10:11:00.900+09:00",
"red": [
"VAN",
"UKR",
"PAK"
],
"blue": [
"VEN",
"ROU",
"QAT"
],
"played": true
},
{
"id": "t2-290",
"type": "ranking",
"number": 290,
"name": "Ranking Match 290",
"field": 4,
"time": "2026-10-10T10:11:00.900+09:00",
"red": [
"GUM",
"MLI",
"HAI"
],
"blue": [
"NGR",
"LTU",
"GER"
],
"played": true
},
{
"id": "t2-292",
"type": "ranking",
"number": 292,
"name": "Ranking Match 292",
"field": 2,
"time": "2026-10-10T10:19:00.900+09:00",
"red": [
"FIN",
"PAR",
"ZIM"
],
"blue": [
"JPN",
"SSD",
"LUX"
],
"played": true
},
{
"id": "t2-294",
"type": "ranking",
"number": 294,
"name": "Ranking Match 294",
"field": 3,
"time": "2026-10-10T10:19:00.900+09:00",
"red": [
"HUN",
"TAN",
"BUL"
],
"blue": [
"SVK",
"SRI",
"GUA"
],
"played": true
},
{
"id": "t2-293",
"type": "ranking",
"number": 293,
"name": "Ranking Match 293",
"field": 5,
"time": "2026-10-10T10:19:00.900+09:00",
"red": [
"ARG",
"STP",
"NAM"
],
"blue": [
"KGZ",
"BRA",
"KAZ"
],
"played": true
},
{
"id": "t2-295",
"type": "ranking",
"number": 295,
"name": "Ranking Match 295",
"field": 1,
"time": "2026-10-10T10:27:00.900+09:00",
"red": [
"ISV",
"PUR",
"UZB"
],
"blue": [
"SYR",
"POL",
"ANG"
],
"played": true
},
{
"id": "t2-297",
"type": "ranking",
"number": 297,
"name": "Ranking Match 297",
"field": 3,
"time": "2026-10-10T10:27:00.900+09:00",
"red": [
"MAW",
"LCA",
"IRL"
],
"blue": [
"CGO",
"TUR",
"DJI"
],
"played": true
},
{
"id": "t2-296",
"type": "ranking",
"number": 296,
"name": "Ranking Match 296",
"field": 4,
"time": "2026-10-10T10:27:00.900+09:00",
"red": [
"ETH",
"YEM",
"DOM"
],
"blue": [
"HKG",
"CAF",
"CAM"
],
"played": true
},
{
"id": "t2-298",
"type": "ranking",
"number": 298,
"name": "Ranking Match 298",
"field": 2,
"time": "2026-10-10T10:35:00.900+09:00",
"red": [
"RSA",
"BAR",
"LAO"
],
"blue": [
"POR",
"TPE",
"BOT"
],
"played": true
},
{
"id": "t2-300",
"type": "ranking",
"number": 300,
"name": "Ranking Match 300",
"field": 3,
"time": "2026-10-10T10:35:00.900+09:00",
"red": [
"GEQ",
"JOR",
"MLT"
],
"blue": [
"FSM",
"MTN",
"IRQ"
],
"played": true
},
{
"id": "t2-299",
"type": "ranking",
"number": 299,
"name": "Ranking Match 299",
"field": 5,
"time": "2026-10-10T10:35:00.900+09:00",
"red": [
"SOM",
"MDV",
"HON"
],
"blue": [
"COK",
"MHL",
"PER"
],
"played": true
},
{
"id": "t2-301",
"type": "ranking",
"number": 301,
"name": "Ranking Match 301",
"field": 1,
"time": "2026-10-10T10:43:00.900+09:00",
"red": [
"JAM",
"AUT",
"LAT"
],
"blue": [
"CHI",
"CZE",
"BIZ"
],
"played": true
},
{
"id": "t2-303",
"type": "ranking",
"number": 303,
"name": "Ranking Match 303",
"field": 3,
"time": "2026-10-10T10:43:00.900+09:00",
"red": [
"NEP",
"CAN",
"LBR"
],
"blue": [
"GHA",
"UGA",
"IVB"
],
"played": true
},
{
"id": "t2-302",
"type": "ranking",
"number": 302,
"name": "Ranking Match 302",
"field": 4,
"time": "2026-10-10T10:43:00.900+09:00",
"red": [
"KIR",
"LBA",
"GBR"
],
"blue": [
"VIN",
"NIG",
"ZAM"
],
"played": true
},
{
"id": "t2-304",
"type": "ranking",
"number": 304,
"name": "Ranking Match 304",
"field": 2,
"time": "2026-10-10T10:51:00.900+09:00",
"red": [
"NOR",
"GRN",
"GBS"
],
"blue": [
"MEX",
"TGA",
"THA"
],
"played": true
},
{
"id": "t2-306",
"type": "ranking",
"number": 306,
"name": "Ranking Match 306",
"field": 3,
"time": "2026-10-10T10:51:00.900+09:00",
"red": [
"EST",
"IND",
"TUN"
],
"blue": [
"MDA",
"BEL",
"MKD"
],
"played": true
},
{
"id": "t2-305",
"type": "ranking",
"number": 305,
"name": "Ranking Match 305",
"field": 5,
"time": "2026-10-10T10:51:00.900+09:00",
"red": [
"COD",
"ITA",
"UAE"
],
"blue": [
"AFG",
"EGY",
"MAD"
],
"played": true
},
{
"id": "t2-307",
"type": "ranking",
"number": 307,
"name": "Ranking Match 307",
"field": 1,
"time": "2026-10-10T10:59:00.900+09:00",
"red": [
"CRO",
"FRA",
"AUS"
],
"blue": [
"SOL",
"BHU",
"GUI"
],
"played": true
},
{
"id": "t2-309",
"type": "ranking",
"number": 309,
"name": "Ranking Match 309",
"field": 3,
"time": "2026-10-10T10:59:00.900+09:00",
"red": [
"GEO",
"CRC",
"OMA"
],
"blue": [
"CIV",
"ROU",
"BAN"
],
"played": true
},
{
"id": "t2-308",
"type": "ranking",
"number": 308,
"name": "Ranking Match 308",
"field": 4,
"time": "2026-10-10T10:59:00.900+09:00",
"red": [
"URU",
"ARU",
"MAS"
],
"blue": [
"AZE",
"NED",
"COL"
],
"played": true
},
{
"id": "t2-310",
"type": "ranking",
"number": 310,
"name": "Ranking Match 310",
"field": 2,
"time": "2026-10-10T11:07:00.900+09:00",
"red": [
"GUY",
"SWZ",
"ANT"
],
"blue": [
"LBN",
"HPE",
"CMR"
],
"played": true
},
{
"id": "t2-312",
"type": "ranking",
"number": 312,
"name": "Ranking Match 312",
"field": 3,
"time": "2026-10-10T11:07:00.900+09:00",
"red": [
"SSD",
"KAZ",
"SEY"
],
"blue": [
"UKR",
"SLE",
"CUB"
],
"played": true
},
{
"id": "t2-311",
"type": "ranking",
"number": 311,
"name": "Ranking Match 311",
"field": 5,
"time": "2026-10-10T11:07:00.900+09:00",
"red": [
"RWA",
"GUA",
"MGL"
],
"blue": [
"PAR",
"USA",
"PLE"
],
"played": true
},
{
"id": "t2-313",
"type": "ranking",
"number": 313,
"name": "Ranking Match 313",
"field": 1,
"time": "2026-10-10T11:15:00.900+09:00",
"red": [
"KOS",
"TTO",
"PAK"
],
"blue": [
"BIH",
"ISR",
"SRI"
],
"played": true
},
{
"id": "t2-315",
"type": "ranking",
"number": 315,
"name": "Ranking Match 315",
"field": 3,
"time": "2026-10-10T11:15:00.900+09:00",
"red": [
"POL",
"MOZ",
"BOL"
],
"blue": [
"HON",
"GER",
"BRA"
],
"played": true
},
{
"id": "t2-314",
"type": "ranking",
"number": 314,
"name": "Ranking Match 314",
"field": 4,
"time": "2026-10-10T11:15:00.900+09:00",
"red": [
"SUD",
"CAM",
"NAM"
],
"blue": [
"DJI",
"VAN",
"BOT"
],
"played": true
},
{
"id": "t2-316",
"type": "ranking",
"number": 316,
"name": "Ranking Match 316",
"field": 2,
"time": "2026-10-10T11:23:00.900+09:00",
"red": [
"MYA",
"YEM",
"HAI"
],
"blue": [
"LUX",
"SLO",
"VEN"
],
"played": true
},
{
"id": "t2-318",
"type": "ranking",
"number": 318,
"name": "Ranking Match 318",
"field": 3,
"time": "2026-10-10T11:23:00.900+09:00",
"red": [
"MDV",
"LAO",
"ALB"
],
"blue": [
"SVK",
"ZIM",
"LBA"
],
"played": true
},
{
"id": "t2-317",
"type": "ranking",
"number": 317,
"name": "Ranking Match 317",
"field": 5,
"time": "2026-10-10T11:23:00.900+09:00",
"red": [
"IRL",
"PER",
"SEN"
],
"blue": [
"ESP",
"DOM",
"ANG"
],
"played": true
},
{
"id": "t2-319",
"type": "ranking",
"number": 319,
"name": "Ranking Match 319",
"field": 1,
"time": "2026-10-10T11:31:00.900+09:00",
"red": [
"UGA",
"SRB",
"COM"
],
"blue": [
"FSM",
"CZE",
"KOR"
],
"played": true
},
{
"id": "t2-321",
"type": "ranking",
"number": 321,
"name": "Ranking Match 321",
"field": 3,
"time": "2026-10-10T11:31:00.900+09:00",
"red": [
"BIZ",
"BEN",
"LTU"
],
"blue": [
"TUR",
"NIG",
"NEP"
],
"played": true
},
{
"id": "t2-320",
"type": "ranking",
"number": 320,
"name": "Ranking Match 320",
"field": 4,
"time": "2026-10-10T11:31:00.900+09:00",
"red": [
"ZAM",
"MNE",
"PAN"
],
"blue": [
"SWE",
"TLS",
"THA"
],
"played": true
},
{
"id": "t2-322",
"type": "ranking",
"number": 322,
"name": "Ranking Match 322",
"field": 2,
"time": "2026-10-10T11:39:00.900+09:00",
"red": [
"BUR",
"ERI",
"ARG"
],
"blue": [
"RUS",
"MHL",
"MEX"
],
"played": true
},
{
"id": "t2-324",
"type": "ranking",
"number": 324,
"name": "Ranking Match 324",
"field": 3,
"time": "2026-10-10T11:39:00.900+09:00",
"red": [
"KIR",
"SOM",
"PNG"
],
"blue": [
"JPN",
"PUR",
"GAB"
],
"played": true
},
{
"id": "t2-323",
"type": "ranking",
"number": 323,
"name": "Ranking Match 323",
"field": 5,
"time": "2026-10-10T11:39:00.900+09:00",
"red": [
"SKN",
"QAT",
"MRI"
],
"blue": [
"IND",
"HKG",
"GAM"
],
"played": true
},
{
"id": "t2-325",
"type": "ranking",
"number": 325,
"name": "Ranking Match 325",
"field": 1,
"time": "2026-10-10T11:47:00.900+09:00",
"red": [
"LES",
"MAD",
"MAR"
],
"blue": [
"GBR",
"NOR",
"BAR"
],
"played": true
},
{
"id": "t2-327",
"type": "ranking",
"number": 327,
"name": "Ranking Match 327",
"field": 3,
"time": "2026-10-10T11:47:00.900+09:00",
"red": [
"UZB",
"VIE",
"MLT"
],
"blue": [
"CGO",
"FRA",
"BRU"
],
"played": true
},
{
"id": "t2-326",
"type": "ranking",
"number": 326,
"name": "Ranking Match 326",
"field": 4,
"time": "2026-10-10T11:47:00.900+09:00",
"red": [
"AFG",
"CAY",
"AUS"
],
"blue": [
"IRQ",
"NED",
"INA"
],
"played": true
},
{
"id": "t2-328",
"type": "ranking",
"number": 328,
"name": "Ranking Match 328",
"field": 2,
"time": "2026-10-10T11:55:00.900+09:00",
"red": [
"TUN",
"MAW",
"MLI"
],
"blue": [
"URU",
"ASA",
"ITA"
],
"played": true
},
{
"id": "t2-330",
"type": "ranking",
"number": 330,
"name": "Ranking Match 330",
"field": 3,
"time": "2026-10-10T11:55:00.900+09:00",
"red": [
"JAM",
"BHU",
"FIN"
],
"blue": [
"MKD",
"TGA",
"GEQ"
],
"played": true
},
{
"id": "t2-329",
"type": "ranking",
"number": 329,
"name": "Ranking Match 329",
"field": 5,
"time": "2026-10-10T11:55:00.900+09:00",
"red": [
"IRI",
"MTN",
"ALG"
],
"blue": [
"CIV",
"KEN",
"SYR"
],
"played": true
},
{
"id": "t2-331",
"type": "ranking",
"number": 331,
"name": "Ranking Match 331",
"field": 1,
"time": "2026-10-10T12:03:00.900+09:00",
"red": [
"MDA",
"GHA",
"FIJ"
],
"blue": [
"COK",
"AZE",
"EGY"
],
"played": true
},
{
"id": "t2-333",
"type": "ranking",
"number": 333,
"name": "Ranking Match 333",
"field": 3,
"time": "2026-10-10T12:03:00.900+09:00",
"red": [
"KGZ",
"ETH",
"GRE"
],
"blue": [
"CHI",
"CRO",
"BEL"
],
"played": true
},
{
"id": "t2-332",
"type": "ranking",
"number": 332,
"name": "Ranking Match 332",
"field": 4,
"time": "2026-10-10T12:03:00.900+09:00",
"red": [
"NCA",
"TOG",
"BUL"
],
"blue": [
"EST",
"LAT",
"LCA"
],
"played": true
},
{
"id": "t2-334",
"type": "ranking",
"number": 334,
"name": "Ranking Match 334",
"field": 2,
"time": "2026-10-10T12:11:00.900+09:00",
"red": [
"NGR",
"TKM",
"DMA"
],
"blue": [
"ESA",
"COL",
"LBR"
],
"played": true
},
{
"id": "t2-336",
"type": "ranking",
"number": 336,
"name": "Ranking Match 336",
"field": 3,
"time": "2026-10-10T12:11:00.900+09:00",
"red": [
"ARU",
"GUM",
"POR"
],
"blue": [
"TJK",
"CPV",
"AUT"
],
"played": true
},
{
"id": "t2-335",
"type": "ranking",
"number": 335,
"name": "Ranking Match 335",
"field": 5,
"time": "2026-10-10T12:11:00.900+09:00",
"red": [
"GRN",
"CHA",
"IVB"
],
"blue": [
"JOR",
"MAS",
"COD"
],
"played": true
},
{
"id": "t2-337",
"type": "ranking",
"number": 337,
"name": "Ranking Match 337",
"field": 1,
"time": "2026-10-10T12:19:00.900+09:00",
"red": [
"UAE",
"SOL",
"CAF"
],
"blue": [
"CAN",
"TPE",
"BLR"
],
"played": true
},
{
"id": "t2-339",
"type": "ranking",
"number": 339,
"name": "Ranking Match 339",
"field": 3,
"time": "2026-10-10T12:19:00.900+09:00",
"red": [
"CHN",
"GUI",
"DEN"
],
"blue": [
"GEO",
"PHI",
"ISV"
],
"played": true
},
{
"id": "t2-338",
"type": "ranking",
"number": 338,
"name": "Ranking Match 338",
"field": 4,
"time": "2026-10-10T12:19:00.900+09:00",
"red": [
"TAN",
"RSA",
"GBS"
],
"blue": [
"VIN",
"ECU",
"STP"
],
"played": true
},
{
"id": "t2-340",
"type": "ranking",
"number": 340,
"name": "Ranking Match 340",
"field": 2,
"time": "2026-10-10T12:27:00.900+09:00",
"red": [
"HUN",
"PNG",
"ALB"
],
"blue": [
"DJI",
"UKR",
"ERI"
],
"played": true
},
{
"id": "t3-1",
"type": "playoff",
"number": 1,
"name": "Round Robin Match 1",
"field": 1,
"time": "2026-10-10T14:22:00.000+09:00",
"red": [
"KAZ",
"OMA",
"TJK",
"MNE"
],
"blue": [
"SRI",
"VIE",
"KGZ",
"GBS"
],
"stage": "Round Robin"
},
{
"id": "t3-2",
"type": "playoff",
"number": 2,
"name": "Round Robin Match 2",
"field": 1,
"time": "2026-10-10T14:30:00.000+09:00",
"red": [
"ESP",
"VIN",
"IRL",
"MTN"
],
"blue": [
"UAE",
"JPN",
"HKG",
"LUX"
],
"stage": "Round Robin"
},
{
"id": "t3-3",
"type": "playoff",
"number": 3,
"name": "Round Robin Match 3",
"field": 1,
"time": "2026-10-10T14:38:00.000+09:00",
"red": [
"MEX",
"POL",
"GRE",
"KOS"
],
"blue": [
"IND",
"BOL",
"BIH",
"COD"
],
"stage": "Round Robin"
},
{
"id": "t3-4",
"type": "playoff",
"number": 4,
"name": "Round Robin Match 4",
"field": 1,
"time": "2026-10-10T14:46:00.000+09:00",
"red": [
"UZB",
"MDA",
"VEN",
"ESA"
],
"blue": [
"CHN",
"TKM",
"CAY",
"TUR"
],
"stage": "Round Robin"
},
{
"id": "t3-5",
"type": "playoff",
"number": 5,
"name": "Round Robin Match 5",
"field": 1,
"time": "2026-10-10T15:09:00.000+09:00",
"red": [
"ESP",
"VIN",
"IRL",
"MTN"
],
"blue": [
"KAZ",
"OMA",
"TJK",
"MNE"
],
"stage": "Round Robin"
},
{
"id": "t3-6",
"type": "playoff",
"number": 6,
"name": "Round Robin Match 6",
"field": 1,
"time": "2026-10-10T15:17:00.000+09:00",
"red": [
"MEX",
"POL",
"GRE",
"KOS"
],
"blue": [
"UAE",
"JPN",
"HKG",
"LUX"
],
"stage": "Round Robin"
},
{
"id": "t3-7",
"type": "playoff",
"number": 7,
"name": "Round Robin Match 7",
"field": 1,
"time": "2026-10-10T15:25:00.000+09:00",
"red": [
"CHN",
"TKM",
"CAY",
"TUR"
],
"blue": [
"SRI",
"VIE",
"KGZ",
"GBS"
],
"stage": "Round Robin"
},
{
"id": "t3-8",
"type": "playoff",
"number": 8,
"name": "Round Robin Match 8",
"field": 1,
"time": "2026-10-10T15:33:00.000+09:00",
"red": [
"UZB",
"MDA",
"VEN",
"ESA"
],
"blue": [
"IND",
"BOL",
"BIH",
"COD"
],
"stage": "Round Robin"
},
{
"id": "t3-9",
"type": "playoff",
"number": 9,
"name": "Round Robin Match 9",
"field": 1,
"time": "2026-10-10T15:57:00.000+09:00",
"red": [
"MEX",
"POL",
"GRE",
"KOS"
],
"blue": [
"KAZ",
"OMA",
"TJK",
"MNE"
],
"stage": "Round Robin"
},
{
"id": "t3-10",
"type": "playoff",
"number": 10,
"name": "Round Robin Match 10",
"field": 1,
"time": "2026-10-10T16:05:00.000+09:00",
"red": [
"CHN",
"TKM",
"CAY",
"TUR"
],
"blue": [
"ESP",
"VIN",
"IRL",
"MTN"
],
"stage": "Round Robin"
},
{
"id": "t3-11",
"type": "playoff",
"number": 11,
"name": "Round Robin Match 11",
"field": 1,
"time": "2026-10-10T16:13:00.000+09:00",
"red": [
"UZB",
"MDA",
"VEN",
"ESA"
],
"blue": [
"UAE",
"JPN",
"HKG",
"LUX"
],
"stage": "Round Robin"
},
{
"id": "t3-12",
"type": "playoff",
"number": 12,
"name": "Round Robin Match 12",
"field": 1,
"time": "2026-10-10T16:21:00.000+09:00",
"red": [
"SRI",
"VIE",
"KGZ",
"GBS"
],
"blue": [
"IND",
"BOL",
"BIH",
"COD"
],
"stage": "Round Robin"
},
{
"id": "t3-13",
"type": "playoff",
"number": 13,
"name": "Round Robin Match 13",
"field": 1,
"time": "2026-10-10T16:45:00.000+09:00",
"red": [
"CHN",
"TKM",
"CAY",
"TUR"
],
"blue": [
"MEX",
"POL",
"GRE",
"KOS"
],
"stage": "Round Robin"
},
{
"id": "t3-14",
"type": "playoff",
"number": 14,
"name": "Round Robin Match 14",
"field": 1,
"time": "2026-10-10T16:53:00.000+09:00",
"red": [
"UZB",
"MDA",
"VEN",
"ESA"
],
"blue": [
"KAZ",
"OMA",
"TJK",
"MNE"
],
"stage": "Round Robin"
},
{
"id": "t3-15",
"type": "playoff",
"number": 15,
"name": "Round Robin Match 15",
"field": 1,
"time": "2026-10-10T17:01:00.000+09:00",
"red": [
"ESP",
"VIN",
"IRL",
"MTN"
],
"blue": [
"IND",
"BOL",
"BIH",
"COD"
],
"stage": "Round Robin"
},
{
"id": "t3-16",
"type": "playoff",
"number": 16,
"name": "Round Robin Match 16",
"field": 1,
"time": "2026-10-10T17:09:00.000+09:00",
"red": [
"UAE",
"JPN",
"HKG",
"LUX"
],
"blue": [
"SRI",
"VIE",
"KGZ",
"GBS"
],
"stage": "Round Robin"
}
],
"alliances": [
{
"n": 1,
"name": "Alliance 1",
"teams": [
"UZB",
"MDA",
"VEN",
"ESA"
],
"rounds": [
"round_robin"
],
"rank": {
"round_robin": 0
}
},
{
"n": 2,
"name": "Alliance 2",
"teams": [
"CHN",
"TKM",
"CAY",
"TUR"
],
"rounds": [
"round_robin"
],
"rank": {
"round_robin": 0
}
},
{
"n": 3,
"name": "Alliance 3",
"teams": [
"MEX",
"POL",
"GRE",
"KOS"
],
"rounds": [
"round_robin"
],
"rank": {
"round_robin": 0
}
},
{
"n": 4,
"name": "Alliance 4",
"teams": [
"KAZ",
"OMA",
"TJK",
"MNE"
],
"rounds": [
"round_robin"
],
"rank": {
"round_robin": 0
}
},
{
"n": 5,
"name": "Alliance 5",
"teams": [
"ESP",
"VIN",
"IRL",
"MTN"
],
"rounds": [
"round_robin"
],
"rank": {
"round_robin": 0
}
},
{
"n": 6,
"name": "Alliance 6",
"teams": [
"UAE",
"JPN",
"HKG",
"LUX"
],
"rounds": [
"round_robin"
],
"rank": {
"round_robin": 0
}
},
{
"n": 7,
"name": "Alliance 7",
"teams": [
"SRI",
"VIE",
"KGZ",
"GBS"
],
"rounds": [
"round_robin"
],
"rank": {
"round_robin": 0
}
},
{
"n": 8,
"name": "Alliance 8",
"teams": [
"IND",
"BOL",
"BIH",
"COD"
],
"rounds": [
"round_robin"
],
"rank": {
"round_robin": 0
}
}
]
};
