/* Generated by tools/build_pronounce.py from tools/pronunciations.json. Do not edit by hand. */
self.FGC_PRONOUNCE = {
"AFG": {
"say": "af-GAN-ih-stan"
},
"ALB": {
"say": "al-BAY-nee-uh"
},
"ALG": {
"say": "al-JEER-ee-uh"
},
"ANG": {
"say": "ang-GOH-luh"
},
"ANT": {
"say": "an-TEE-guh and bar-BOO-duh",
"tip": "U is silent in Antigua"
},
"ARG": {
"say": "ar-jen-TEE-nuh"
},
"AUS": {
"say": "aw-STRAYL-yuh"
},
"AUT": {
"say": "AW-stree-uh"
},
"AZE": {
"say": "ah-zer-by-JAHN"
},
"BAN": {
"say": "bang-gluh-DESH"
},
"BAR": {
"say": "bar-BAY-dohs"
},
"BEL": {
"say": "BEL-jum"
},
"BEN": {
"say": "beh-NEEN"
},
"BHU": {
"say": "boo-TAHN"
},
"BIH": {
"say": "BOZ-nee-uh and hert-suh-goh-VEE-nuh"
},
"BIZ": {
"say": "beh-LEEZ"
},
"BOL": {
"say": "boh-LIV-ee-uh"
},
"BOT": {
"say": "baht-SWAH-nuh"
},
"BRA": {
"say": "bruh-ZIL"
},
"BRU": {
"say": "broo-NYE dah-roo-suh-LAHM"
},
"BUL": {
"say": "bul-GAIR-ee-uh"
},
"BUR": {
"say": "bur-KEE-nuh FAH-soh"
},
"CAF": {
"say": "SEN-trul AF-rih-kun ree-PUB-lik"
},
"CAM": {
"say": "kam-BOH-dee-uh"
},
"CAN": {
"say": "KAN-uh-duh"
},
"CAY": {
"say": "KAY-mun EYE-lundz"
},
"CGO": {
"say": "KONG-goh"
},
"CHA": {
"say": "CHAD"
},
"CHI": {
"say": "CHIL-ee"
},
"CHN": {
"say": "PEE-pulz ree-PUB-lik uhv CHY-nuh"
},
"CIV": {
"say": "KOHT deev-WAHR"
},
"CMR": {
"say": "kam-uh-ROON"
},
"COD": {
"say": "dem-uh-KRAT-ik ree-PUB-lik uhv the KONG-goh"
},
"COK": {
"say": "KOOK EYE-lundz"
},
"COL": {
"say": "kuh-LUM-bee-uh"
},
"COM": {
"say": "KAH-muh-rohs"
},
"CPV": {
"say": "KAH-boh VAIR-day"
},
"CRC": {
"say": "KOH-stuh REE-kuh"
},
"CRO": {
"say": "kroh-AY-shuh"
},
"CUB": {
"say": "KYOO-buh"
},
"CZE": {
"say": "CHEK-ee-uh"
},
"DEN": {
"say": "DEN-mark"
},
"DJI": {
"say": "jih-BOO-tee"
},
"DMA": {
"say": "dom-ih-NEE-kuh"
},
"DOM": {
"say": "duh-MIN-ih-kun ree-PUB-lik"
},
"ECU": {
"say": "EK-wuh-dor"
},
"EGY": {
"say": "EE-jipt"
},
"ERI": {
"say": "air-ih-TRAY-uh"
},
"ESA": {
"say": "el SAL-vuh-dor"
},
"ESP": {
"say": "SPAYN"
},
"EST": {
"say": "eh-STOH-nee-uh"
},
"ETH": {
"say": "ee-thee-OH-pee-uh"
},
"FIJ": {
"say": "FEE-jee"
},
"FIN": {
"say": "FIN-lund"
},
"FRA": {
"say": "FRANS"
},
"GAB": {
"say": "gah-BOHN"
},
"GAM": {
"say": "GAM-bee-uh"
},
"GBR": {
"say": "GRAYT BRIT-un"
},
"GBS": {
"say": "GIN-ee bih-SOW",
"tip": "SOW rhymes with cow"
},
"GEO": {
"say": "JOR-juh"
},
"GEQ": {
"say": "ek-wuh-TOR-ee-ul GIN-ee"
},
"GER": {
"say": "JER-muh-nee"
},
"GHA": {
"say": "GAH-nuh"
},
"GRE": {
"say": "GREES"
},
"GRN": {
"say": "greh-NAY-duh"
},
"GUA": {
"say": "gwah-tuh-MAH-luh"
},
"GUI": {
"say": "GIN-ee"
},
"GUY": {
"say": "gy-AH-nuh"
},
"HAI": {
"say": "HAY-tee"
},
"HKG": {
"say": "HONG KONG, CHY-nuh"
},
"HON": {
"say": "hon-DOOR-us"
},
"HPE": {
"say": "HOHP (ref-yoo-JEEZ)"
},
"HUN": {
"say": "HUNG-guh-ree"
},
"INA": {
"say": "in-duh-NEE-zhuh"
},
"IND": {
"say": "IN-dee-uh"
},
"IRI": {
"say": "iz-LAHM-ik ree-PUB-lik uhv ih-RAHN"
},
"IRL": {
"say": "IRE-lund"
},
"IRQ": {
"say": "ih-RAHK"
},
"ISR": {
"say": "IZ-ray-ul"
},
"ITA": {
"say": "IT-uh-lee"
},
"JAM": {
"say": "juh-MAY-kuh"
},
"JOR": {
"say": "JOR-dun"
},
"JPN": {
"say": "juh-PAN"
},
"KAZ": {
"say": "KAH-zahk-stahn"
},
"KEN": {
"say": "KEN-yuh"
},
"KGZ": {
"say": "KEER-gih-stahn"
},
"KIR": {
"say": "KEER-ih-bahss"
},
"KOR": {
"say": "ree-PUB-lik uhv kuh-REE-uh"
},
"KOS": {
"say": "KOH-suh-voh"
},
"LAO": {
"say": "LOW PEE-pulz dem-uh-KRAT-ik ree-PUB-lik",
"tip": "LOW rhymes with cow"
},
"LAT": {
"say": "LAT-vee-uh"
},
"LBA": {
"say": "LIB-ee-uh"
},
"LBN": {
"say": "LEB-uh-non"
},
"LBR": {
"say": "ly-BEER-ee-uh"
},
"LCA": {
"say": "saynt LOO-shuh"
},
"LES": {
"say": "leh-SOO-too"
},
"LTU": {
"say": "lith-oo-AY-nee-uh"
},
"LUX": {
"say": "LUK-sum-burg"
},
"MAD": {
"say": "mad-uh-GAS-kar"
},
"MAR": {
"say": "muh-ROK-oh"
},
"MAS": {
"say": "muh-LAY-zhuh"
},
"MAW": {
"say": "muh-LAH-wee"
},
"MDA": {
"say": "ree-PUB-lik uhv mol-DOH-vuh"
},
"MDV": {
"say": "MAWL-deevz"
},
"MEX": {
"say": "MEK-sih-koh"
},
"MGL": {
"say": "mon-GOH-lee-uh"
},
"MKD": {
"say": "north mas-uh-DOH-nee-uh"
},
"MLI": {
"say": "MAH-lee"
},
"MLT": {
"say": "MAWL-tuh"
},
"MNE": {
"say": "mon-tuh-NAY-groh"
},
"MOZ": {
"say": "moh-zam-BEEK"
},
"MRI": {
"say": "muh-RISH-us"
},
"MTN": {
"say": "mor-ih-TAY-nee-uh"
},
"MYA": {
"say": "MEE-ahn-mar"
},
"NAM": {
"say": "nuh-MIB-ee-uh"
},
"NCA": {
"say": "nik-uh-RAH-gwuh"
},
"NED": {
"say": "NETH-er-lundz"
},
"NEP": {
"say": "nuh-PAWL"
},
"NGR": {
"say": "ny-JEER-ee-uh"
},
"NIG": {
"say": "nee-ZHAIR"
},
"NOR": {
"say": "NOR-way"
},
"OMA": {
"say": "oh-MAHN"
},
"PAK": {
"say": "PAK-ih-stahn"
},
"PAN": {
"say": "PAN-uh-mah"
},
"PAR": {
"say": "PAR-uh-gway"
},
"PER": {
"say": "puh-ROO"
},
"PHI": {
"say": "FIL-ih-peenz"
},
"PLE": {
"say": "PAL-eh-styne"
},
"PNG": {
"say": "PAH-poo-uh noo GIN-ee"
},
"POL": {
"say": "POH-lund"
},
"POR": {
"say": "POR-chuh-gul"
},
"QAT": {
"say": "KAH-tar"
},
"ROU": {
"say": "roh-MAY-nee-uh"
},
"RSA": {
"say": "sowth AF-rih-kuh"
},
"RWA": {
"say": "roo-AHN-duh"
},
"SEN": {
"say": "sen-ih-GAWL"
},
"SEY": {
"say": "say-SHELLS"
},
"SKN": {
"say": "saynt KITS and NEE-vis"
},
"SLE": {
"say": "see-AIR-uh lee-OHN"
},
"SLO": {
"say": "sloh-VEE-nee-uh"
},
"SOL": {
"say": "SOL-uh-mun EYE-lundz"
},
"SOM": {
"say": "suh-MAHL-ee-uh"
},
"SRB": {
"say": "SER-bee-uh"
},
"SRI": {
"say": "sree LAHNG-kuh"
},
"STP": {
"say": "SOW toh-MAY and PRIN-sih-pay",
"tip": "SOW rhymes with cow"
},
"SUD": {
"say": "soo-DAN"
},
"SVK": {
"say": "sloh-VAH-kee-uh"
},
"SWE": {
"say": "SWEE-dun"
},
"SWZ": {
"say": "es-wah-TEE-nee"
},
"SYR": {
"say": "SEER-ee-un AIR-ub ree-PUB-lik"
},
"TAN": {
"say": "yoo-NY-tid ree-PUB-lik uhv tan-zuh-NEE-uh"
},
"THA": {
"say": "TY-land"
},
"TJK": {
"say": "tah-JIK-ih-stahn"
},
"TKM": {
"say": "turk-MEN-ih-stahn"
},
"TLS": {
"say": "TEE-mor LESH-tay"
},
"TOG": {
"say": "TOH-goh"
},
"TPE": {
"say": "chy-NEEZ ty-PAY"
},
"TTO": {
"say": "TRIN-ih-dad and tuh-BAY-goh"
},
"TUN": {
"say": "too-NEE-zhuh"
},
"TUR": {
"say": "TOOR-kee-yay"
},
"UAE": {
"say": "yoo-NY-tid AIR-ub EM-ih-ruts"
},
"UGA": {
"say": "yoo-GAHN-duh"
},
"UKR": {
"say": "yoo-KRAYN"
},
"URU": {
"say": "YOOR-uh-gway"
},
"USA": {
"say": "yoo-NY-tid STAYTS uhv uh-MAIR-ih-kuh"
},
"UZB": {
"say": "ooz-BEK-ih-stahn"
},
"VAN": {
"say": "vah-noo-AH-too"
},
"VEN": {
"say": "ven-eh-ZWAY-luh"
},
"VIE": {
"say": "vee-et-NAHM"
},
"VIN": {
"say": "saynt VIN-sent and the GREN-uh-deenz"
},
"YEM": {
"say": "YEM-en"
},
"ZAM": {
"say": "ZAM-bee-uh"
},
"ZIM": {
"say": "zim-BAHB-way"
}
};
