#!/usr/bin/env python3
"""Build pronounce.js (how to say each team's name) from tools/pronunciations.json.

Usage (from the repo root):  python3 tools/build_pronounce.py

tools/pronunciations.json maps a team's display name, exactly as in data.js (the
results.first.global name minus "Team "), to {"say": respelling, "tip": optional note}.
Respelling key: CAPITALS = stressed syllable; ay=day, ah=father, aw=law, ee=see,
eye/y=fly, oh=go, oo=boot, ow=cow, zh=measure, g always hard.
pronounce.js is keyed by team code so it follows data.js. Every team must have an entry,
and every entry must be a team (names that are not in data.js are reported).
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    s = open(os.path.join(ROOT, "data.js"), encoding="utf-8").read()
    teams = json.loads(s[s.index("{"):s.rindex(";")])["teams"]
    src = json.load(open(os.path.join(ROOT, "tools", "pronunciations.json"), encoding="utf-8"))
    by_name = {(t.get("country") or t["name"]): c for c, t in teams.items()}
    out, unknown = {}, []
    for name, v in src.items():
        if name not in by_name:
            unknown.append(name)
            continue
        out[by_name[name]] = {k: v[k] for k in ("say", "tip") if v.get(k)}
    missing = sorted(n for n, c in by_name.items() if c not in out)
    with open(os.path.join(ROOT, "pronounce.js"), "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/build_pronounce.py from tools/pronunciations.json. Do not edit by hand. */\n")
        f.write("self.FGC_PRONOUNCE = ")
        json.dump(dict(sorted(out.items())), f, ensure_ascii=False, indent=0)
        f.write(";\n")
    print(f"{len(out)} of {len(teams)} teams written to pronounce.js")
    if unknown:
        print("Not a team in data.js (ignored):", ", ".join(unknown))
    if missing:
        print("No pronunciation for:", ", ".join(missing))
        sys.exit(1)


if __name__ == "__main__":
    main()
