#!/usr/bin/env python3
"""Build data.js and flags/ from https://results.first.global/ (the authority for
country names, flags and the match schedule).

Usage (from the repo root):  python3 tools/fetch_fgc_data.py

The results site is a Next.js app; the schedule and team list are embedded in the
home page as __NEXT_DATA__ JSON. Flags are the site's own SVGs from
/static/flags/4x3/<code>.svg, cached in tools/.flag-cache/ and then rendered to
small PNGs in flags/ by tools/rasterize_flags.mjs (some official SVGs are >1 MB).
Played/score state is deliberately NOT imported so the queue sheet starts clean.
"""
import json
import os
import re
import sys
import urllib.request
from datetime import datetime, timezone

BASE = "https://results.first.global"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FLAG_DIR = os.path.join(ROOT, "tools", ".flag-cache")
# Special (non-ISO) flag codes, mirrored from the site's getFlagUrl().
SPECIAL_FLAGS = {"10": "10_hope", "11": "11_south-america", "12": "12_oceania",
                 "13": "13_north-america", "14": "14_europe"}


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "FGC-queue-sheet-builder"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def match_type(name):
    n = name.lower()
    if "practice" in n:
        return "practice"
    if "ranking" in n or "qualif" in n:
        return "ranking"
    return "playoff"


def main():
    html = get(BASE + "/").decode("utf-8")
    m = re.search(r'<script id="__NEXT_DATA__" type="application/json">(.*?)</script>', html, re.S)
    if not m:
        sys.exit("Could not find __NEXT_DATA__ on the results page; the site layout changed.")
    data = json.loads(m.group(1))["props"]["pageProps"]["data"]

    # Teams: names exactly as published by FIRST Global.
    teams = {}
    for r in data.get("rankings", []):
        t = r["team"]
        teams[t["country"]] = {"name": t["name"], "cc": t["countryCode"]}
    for mt in data["matches"]:
        for p in mt["participants"]:
            if p["country"] not in teams:
                sys.exit(f"Team {p['country']} appears in a match but has no published name.")

    os.makedirs(FLAG_DIR, exist_ok=True)
    for code, t in sorted(teams.items()):
        cc = t.pop("cc").lower()
        fname = SPECIAL_FLAGS.get(cc, cc) + ".svg"
        path = os.path.join(FLAG_DIR, fname)
        if not os.path.exists(path):
            svg = get(f"{BASE}/static/flags/4x3/{fname}")
            if b"<svg" not in svg[:2000]:
                sys.exit(f"Flag for {code} ({fname}) is not an SVG.")
            with open(path, "wb") as f:
                f.write(svg)
        t["flag"] = "flags/" + fname[:-4] + ".png"
        # Display name: the published name minus the generic "Team " prefix, for country
        # teams only (special teams such as "Team Hope (Refugees)" keep their full name).
        if cc not in SPECIAL_FLAGS and t["name"].startswith("Team "):
            t["country"] = t["name"][len("Team "):]

    matches = []
    for mt in data["matches"]:
        num = re.search(r"(\d+)\s*$", mt["name"])
        ps = sorted(mt["participants"], key=lambda p: p["station"])
        matches.append({
            "id": f"{mt['tournamentKey']}-{mt['id']}",
            "type": match_type(mt["name"]),
            "number": int(num.group(1)) if num else mt["id"],
            "name": mt["name"],
            "field": mt["field"],
            "time": mt["scheduledTime"],
            "red": [p["country"] for p in ps if p["station"] < 20],
            "blue": [p["country"] for p in ps if p["station"] > 20],
        })
    matches.sort(key=lambda x: (x["time"], x["field"]))

    event_key = data["matches"][0]["eventKey"] if data["matches"] else "FGC"
    fetched = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out = {
        "event": {"id": event_key, "name": "2026 FIRST Global Challenge", "tz": "Asia/Seoul",
                  "source": f"results.first.global, fetched {fetched}"},
        "teams": dict(sorted(teams.items())),
        "matches": matches,
    }
    with open(os.path.join(ROOT, "data.js"), "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/fetch_fgc_data.py from results.first.global. Do not edit by hand. */\n")
        f.write("self.FGC_DATA = ")
        json.dump(out, f, ensure_ascii=False, indent=0)
        f.write(";\n")
    print(f"{len(teams)} teams, {len(matches)} matches written. Now run: node tools/rasterize_flags.mjs")


if __name__ == "__main__":
    main()
